// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/singorix_proto/singorix_control_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
#include "galbot/core_proto/wrapper.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[12]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
namespace galbot {
namespace singorix_proto {
class DynamicsConfig;
class DynamicsConfigDefaultTypeInternal;
extern DynamicsConfigDefaultTypeInternal _DynamicsConfig_default_instance_;
class DynamicsConfig_ParamMapEntry_DoNotUse;
class DynamicsConfig_ParamMapEntry_DoNotUseDefaultTypeInternal;
extern DynamicsConfig_ParamMapEntry_DoNotUseDefaultTypeInternal _DynamicsConfig_ParamMapEntry_DoNotUse_default_instance_;
class FilterConfig;
class FilterConfigDefaultTypeInternal;
extern FilterConfigDefaultTypeInternal _FilterConfig_default_instance_;
class FilterConfig_ParamMapEntry_DoNotUse;
class FilterConfig_ParamMapEntry_DoNotUseDefaultTypeInternal;
extern FilterConfig_ParamMapEntry_DoNotUseDefaultTypeInternal _FilterConfig_ParamMapEntry_DoNotUse_default_instance_;
class JointLimits;
class JointLimitsDefaultTypeInternal;
extern JointLimitsDefaultTypeInternal _JointLimits_default_instance_;
class JointPvtConfig;
class JointPvtConfigDefaultTypeInternal;
extern JointPvtConfigDefaultTypeInternal _JointPvtConfig_default_instance_;
class JointPvtConfig_FilterConfigMapEntry_DoNotUse;
class JointPvtConfig_FilterConfigMapEntry_DoNotUseDefaultTypeInternal;
extern JointPvtConfig_FilterConfigMapEntry_DoNotUseDefaultTypeInternal _JointPvtConfig_FilterConfigMapEntry_DoNotUse_default_instance_;
class JointPvtConfig_LimitMapEntry_DoNotUse;
class JointPvtConfig_LimitMapEntry_DoNotUseDefaultTypeInternal;
extern JointPvtConfig_LimitMapEntry_DoNotUseDefaultTypeInternal _JointPvtConfig_LimitMapEntry_DoNotUse_default_instance_;
class JointPvtConfig_PidConfigMapEntry_DoNotUse;
class JointPvtConfig_PidConfigMapEntry_DoNotUseDefaultTypeInternal;
extern JointPvtConfig_PidConfigMapEntry_DoNotUseDefaultTypeInternal _JointPvtConfig_PidConfigMapEntry_DoNotUse_default_instance_;
class PIDConfig;
class PIDConfigDefaultTypeInternal;
extern PIDConfigDefaultTypeInternal _PIDConfig_default_instance_;
class SingoriXControlConfig;
class SingoriXControlConfigDefaultTypeInternal;
extern SingoriXControlConfigDefaultTypeInternal _SingoriXControlConfig_default_instance_;
class SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse;
class SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUseDefaultTypeInternal;
extern SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUseDefaultTypeInternal _SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse_default_instance_;
}  // namespace singorix_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::singorix_proto::DynamicsConfig* Arena::CreateMaybeMessage<::galbot::singorix_proto::DynamicsConfig>(Arena*);
template<> ::galbot::singorix_proto::DynamicsConfig_ParamMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::DynamicsConfig_ParamMapEntry_DoNotUse>(Arena*);
template<> ::galbot::singorix_proto::FilterConfig* Arena::CreateMaybeMessage<::galbot::singorix_proto::FilterConfig>(Arena*);
template<> ::galbot::singorix_proto::FilterConfig_ParamMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::FilterConfig_ParamMapEntry_DoNotUse>(Arena*);
template<> ::galbot::singorix_proto::JointLimits* Arena::CreateMaybeMessage<::galbot::singorix_proto::JointLimits>(Arena*);
template<> ::galbot::singorix_proto::JointPvtConfig* Arena::CreateMaybeMessage<::galbot::singorix_proto::JointPvtConfig>(Arena*);
template<> ::galbot::singorix_proto::JointPvtConfig_FilterConfigMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::JointPvtConfig_FilterConfigMapEntry_DoNotUse>(Arena*);
template<> ::galbot::singorix_proto::JointPvtConfig_LimitMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::JointPvtConfig_LimitMapEntry_DoNotUse>(Arena*);
template<> ::galbot::singorix_proto::JointPvtConfig_PidConfigMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::JointPvtConfig_PidConfigMapEntry_DoNotUse>(Arena*);
template<> ::galbot::singorix_proto::PIDConfig* Arena::CreateMaybeMessage<::galbot::singorix_proto::PIDConfig>(Arena*);
template<> ::galbot::singorix_proto::SingoriXControlConfig* Arena::CreateMaybeMessage<::galbot::singorix_proto::SingoriXControlConfig>(Arena*);
template<> ::galbot::singorix_proto::SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace singorix_proto {

// ===================================================================

class JointLimits PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.JointLimits) */ {
 public:
  inline JointLimits() : JointLimits(nullptr) {}
  virtual ~JointLimits();

  JointLimits(const JointLimits& from);
  JointLimits(JointLimits&& from) noexcept
    : JointLimits() {
    *this = ::std::move(from);
  }

  inline JointLimits& operator=(const JointLimits& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointLimits& operator=(JointLimits&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JointLimits& default_instance();

  static inline const JointLimits* internal_default_instance() {
    return reinterpret_cast<const JointLimits*>(
               &_JointLimits_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JointLimits& a, JointLimits& b) {
    a.Swap(&b);
  }
  inline void Swap(JointLimits* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointLimits* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JointLimits* New() const final {
    return CreateMaybeMessage<JointLimits>(nullptr);
  }

  JointLimits* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JointLimits>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JointLimits& from);
  void MergeFrom(const JointLimits& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JointLimits* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.JointLimits";
  }
  protected:
  explicit JointLimits(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionMinFieldNumber = 1,
    kPositionMaxFieldNumber = 2,
    kVelocityLimitFieldNumber = 3,
    kAccelerationLimitFieldNumber = 4,
    kJerkLimitFieldNumber = 5,
    kSnapLimitFieldNumber = 6,
    kEffortLimitFieldNumber = 7,
    kCurrentLimitFieldNumber = 8,
  };
  // double position_min = 1;
  void clear_position_min();
  double position_min() const;
  void set_position_min(double value);
  private:
  double _internal_position_min() const;
  void _internal_set_position_min(double value);
  public:

  // double position_max = 2;
  void clear_position_max();
  double position_max() const;
  void set_position_max(double value);
  private:
  double _internal_position_max() const;
  void _internal_set_position_max(double value);
  public:

  // double velocity_limit = 3;
  void clear_velocity_limit();
  double velocity_limit() const;
  void set_velocity_limit(double value);
  private:
  double _internal_velocity_limit() const;
  void _internal_set_velocity_limit(double value);
  public:

  // double acceleration_limit = 4;
  void clear_acceleration_limit();
  double acceleration_limit() const;
  void set_acceleration_limit(double value);
  private:
  double _internal_acceleration_limit() const;
  void _internal_set_acceleration_limit(double value);
  public:

  // double jerk_limit = 5;
  void clear_jerk_limit();
  double jerk_limit() const;
  void set_jerk_limit(double value);
  private:
  double _internal_jerk_limit() const;
  void _internal_set_jerk_limit(double value);
  public:

  // double snap_limit = 6;
  void clear_snap_limit();
  double snap_limit() const;
  void set_snap_limit(double value);
  private:
  double _internal_snap_limit() const;
  void _internal_set_snap_limit(double value);
  public:

  // double effort_limit = 7;
  void clear_effort_limit();
  double effort_limit() const;
  void set_effort_limit(double value);
  private:
  double _internal_effort_limit() const;
  void _internal_set_effort_limit(double value);
  public:

  // double current_limit = 8;
  void clear_current_limit();
  double current_limit() const;
  void set_current_limit(double value);
  private:
  double _internal_current_limit() const;
  void _internal_set_current_limit(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.JointLimits)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double position_min_;
  double position_max_;
  double velocity_limit_;
  double acceleration_limit_;
  double jerk_limit_;
  double snap_limit_;
  double effort_limit_;
  double current_limit_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class PIDConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.PIDConfig) */ {
 public:
  inline PIDConfig() : PIDConfig(nullptr) {}
  virtual ~PIDConfig();

  PIDConfig(const PIDConfig& from);
  PIDConfig(PIDConfig&& from) noexcept
    : PIDConfig() {
    *this = ::std::move(from);
  }

  inline PIDConfig& operator=(const PIDConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline PIDConfig& operator=(PIDConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PIDConfig& default_instance();

  static inline const PIDConfig* internal_default_instance() {
    return reinterpret_cast<const PIDConfig*>(
               &_PIDConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PIDConfig& a, PIDConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(PIDConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PIDConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PIDConfig* New() const final {
    return CreateMaybeMessage<PIDConfig>(nullptr);
  }

  PIDConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PIDConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PIDConfig& from);
  void MergeFrom(const PIDConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PIDConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.PIDConfig";
  }
  protected:
  explicit PIDConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKpFieldNumber = 1,
    kKiFieldNumber = 2,
    kKdFieldNumber = 3,
    kILimitFieldNumber = 4,
    kISepThrFieldNumber = 5,
  };
  // double kp = 1;
  void clear_kp();
  double kp() const;
  void set_kp(double value);
  private:
  double _internal_kp() const;
  void _internal_set_kp(double value);
  public:

  // double ki = 2;
  void clear_ki();
  double ki() const;
  void set_ki(double value);
  private:
  double _internal_ki() const;
  void _internal_set_ki(double value);
  public:

  // double kd = 3;
  void clear_kd();
  double kd() const;
  void set_kd(double value);
  private:
  double _internal_kd() const;
  void _internal_set_kd(double value);
  public:

  // double i_limit = 4;
  void clear_i_limit();
  double i_limit() const;
  void set_i_limit(double value);
  private:
  double _internal_i_limit() const;
  void _internal_set_i_limit(double value);
  public:

  // double i_sep_thr = 5;
  void clear_i_sep_thr();
  double i_sep_thr() const;
  void set_i_sep_thr(double value);
  private:
  double _internal_i_sep_thr() const;
  void _internal_set_i_sep_thr(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.PIDConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double kp_;
  double ki_;
  double kd_;
  double i_limit_;
  double i_sep_thr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class FilterConfig_ParamMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<FilterConfig_ParamMapEntry_DoNotUse, 
    std::string, ::galbot::core_proto::Value,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<FilterConfig_ParamMapEntry_DoNotUse, 
    std::string, ::galbot::core_proto::Value,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  FilterConfig_ParamMapEntry_DoNotUse();
  explicit FilterConfig_ParamMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const FilterConfig_ParamMapEntry_DoNotUse& other);
  static const FilterConfig_ParamMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const FilterConfig_ParamMapEntry_DoNotUse*>(&_FilterConfig_ParamMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.FilterConfig.ParamMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class FilterConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.FilterConfig) */ {
 public:
  inline FilterConfig() : FilterConfig(nullptr) {}
  virtual ~FilterConfig();

  FilterConfig(const FilterConfig& from);
  FilterConfig(FilterConfig&& from) noexcept
    : FilterConfig() {
    *this = ::std::move(from);
  }

  inline FilterConfig& operator=(const FilterConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline FilterConfig& operator=(FilterConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FilterConfig& default_instance();

  static inline const FilterConfig* internal_default_instance() {
    return reinterpret_cast<const FilterConfig*>(
               &_FilterConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FilterConfig& a, FilterConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(FilterConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FilterConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FilterConfig* New() const final {
    return CreateMaybeMessage<FilterConfig>(nullptr);
  }

  FilterConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FilterConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FilterConfig& from);
  void MergeFrom(const FilterConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FilterConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.FilterConfig";
  }
  protected:
  explicit FilterConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kParamMapFieldNumber = 4,
    kFilterImplFieldNumber = 1,
    kCutoffFrequencyFieldNumber = 2,
    kSamplingFrequencyFieldNumber = 3,
  };
  // map<string, .galbot.core_proto.Value> param_map = 4;
  int param_map_size() const;
  private:
  int _internal_param_map_size() const;
  public:
  void clear_param_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
      _internal_param_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
      _internal_mutable_param_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
      param_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
      mutable_param_map();

  // string filter_impl = 1;
  void clear_filter_impl();
  const std::string& filter_impl() const;
  void set_filter_impl(const std::string& value);
  void set_filter_impl(std::string&& value);
  void set_filter_impl(const char* value);
  void set_filter_impl(const char* value, size_t size);
  std::string* mutable_filter_impl();
  std::string* release_filter_impl();
  void set_allocated_filter_impl(std::string* filter_impl);
  private:
  const std::string& _internal_filter_impl() const;
  void _internal_set_filter_impl(const std::string& value);
  std::string* _internal_mutable_filter_impl();
  public:

  // double cutoff_frequency = 2;
  void clear_cutoff_frequency();
  double cutoff_frequency() const;
  void set_cutoff_frequency(double value);
  private:
  double _internal_cutoff_frequency() const;
  void _internal_set_cutoff_frequency(double value);
  public:

  // double sampling_frequency = 3;
  void clear_sampling_frequency();
  double sampling_frequency() const;
  void set_sampling_frequency(double value);
  private:
  double _internal_sampling_frequency() const;
  void _internal_set_sampling_frequency(double value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.FilterConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      FilterConfig_ParamMapEntry_DoNotUse,
      std::string, ::galbot::core_proto::Value,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> param_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filter_impl_;
  double cutoff_frequency_;
  double sampling_frequency_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class DynamicsConfig_ParamMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<DynamicsConfig_ParamMapEntry_DoNotUse, 
    std::string, ::galbot::core_proto::Value,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<DynamicsConfig_ParamMapEntry_DoNotUse, 
    std::string, ::galbot::core_proto::Value,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  DynamicsConfig_ParamMapEntry_DoNotUse();
  explicit DynamicsConfig_ParamMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const DynamicsConfig_ParamMapEntry_DoNotUse& other);
  static const DynamicsConfig_ParamMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const DynamicsConfig_ParamMapEntry_DoNotUse*>(&_DynamicsConfig_ParamMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.DynamicsConfig.ParamMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[4];
  }

  public:
};

// -------------------------------------------------------------------

class DynamicsConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.DynamicsConfig) */ {
 public:
  inline DynamicsConfig() : DynamicsConfig(nullptr) {}
  virtual ~DynamicsConfig();

  DynamicsConfig(const DynamicsConfig& from);
  DynamicsConfig(DynamicsConfig&& from) noexcept
    : DynamicsConfig() {
    *this = ::std::move(from);
  }

  inline DynamicsConfig& operator=(const DynamicsConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline DynamicsConfig& operator=(DynamicsConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DynamicsConfig& default_instance();

  static inline const DynamicsConfig* internal_default_instance() {
    return reinterpret_cast<const DynamicsConfig*>(
               &_DynamicsConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(DynamicsConfig& a, DynamicsConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(DynamicsConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DynamicsConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DynamicsConfig* New() const final {
    return CreateMaybeMessage<DynamicsConfig>(nullptr);
  }

  DynamicsConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DynamicsConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DynamicsConfig& from);
  void MergeFrom(const DynamicsConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DynamicsConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.DynamicsConfig";
  }
  protected:
  explicit DynamicsConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kParamMapFieldNumber = 2,
    kDynamicsImplFieldNumber = 1,
  };
  // map<string, .galbot.core_proto.Value> param_map = 2;
  int param_map_size() const;
  private:
  int _internal_param_map_size() const;
  public:
  void clear_param_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
      _internal_param_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
      _internal_mutable_param_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
      param_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
      mutable_param_map();

  // string dynamics_impl = 1;
  void clear_dynamics_impl();
  const std::string& dynamics_impl() const;
  void set_dynamics_impl(const std::string& value);
  void set_dynamics_impl(std::string&& value);
  void set_dynamics_impl(const char* value);
  void set_dynamics_impl(const char* value, size_t size);
  std::string* mutable_dynamics_impl();
  std::string* release_dynamics_impl();
  void set_allocated_dynamics_impl(std::string* dynamics_impl);
  private:
  const std::string& _internal_dynamics_impl() const;
  void _internal_set_dynamics_impl(const std::string& value);
  std::string* _internal_mutable_dynamics_impl();
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.DynamicsConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      DynamicsConfig_ParamMapEntry_DoNotUse,
      std::string, ::galbot::core_proto::Value,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> param_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dynamics_impl_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class JointPvtConfig_LimitMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JointPvtConfig_LimitMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::JointLimits,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JointPvtConfig_LimitMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::JointLimits,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  JointPvtConfig_LimitMapEntry_DoNotUse();
  explicit JointPvtConfig_LimitMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JointPvtConfig_LimitMapEntry_DoNotUse& other);
  static const JointPvtConfig_LimitMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JointPvtConfig_LimitMapEntry_DoNotUse*>(&_JointPvtConfig_LimitMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.JointPvtConfig.LimitMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[6];
  }

  public:
};

// -------------------------------------------------------------------

class JointPvtConfig_PidConfigMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JointPvtConfig_PidConfigMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::PIDConfig,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JointPvtConfig_PidConfigMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::PIDConfig,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  JointPvtConfig_PidConfigMapEntry_DoNotUse();
  explicit JointPvtConfig_PidConfigMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JointPvtConfig_PidConfigMapEntry_DoNotUse& other);
  static const JointPvtConfig_PidConfigMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JointPvtConfig_PidConfigMapEntry_DoNotUse*>(&_JointPvtConfig_PidConfigMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.JointPvtConfig.PidConfigMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[7];
  }

  public:
};

// -------------------------------------------------------------------

class JointPvtConfig_FilterConfigMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JointPvtConfig_FilterConfigMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::FilterConfig,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JointPvtConfig_FilterConfigMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::FilterConfig,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  JointPvtConfig_FilterConfigMapEntry_DoNotUse();
  explicit JointPvtConfig_FilterConfigMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JointPvtConfig_FilterConfigMapEntry_DoNotUse& other);
  static const JointPvtConfig_FilterConfigMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JointPvtConfig_FilterConfigMapEntry_DoNotUse*>(&_JointPvtConfig_FilterConfigMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.JointPvtConfig.FilterConfigMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[8];
  }

  public:
};

// -------------------------------------------------------------------

class JointPvtConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.JointPvtConfig) */ {
 public:
  inline JointPvtConfig() : JointPvtConfig(nullptr) {}
  virtual ~JointPvtConfig();

  JointPvtConfig(const JointPvtConfig& from);
  JointPvtConfig(JointPvtConfig&& from) noexcept
    : JointPvtConfig() {
    *this = ::std::move(from);
  }

  inline JointPvtConfig& operator=(const JointPvtConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointPvtConfig& operator=(JointPvtConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JointPvtConfig& default_instance();

  static inline const JointPvtConfig* internal_default_instance() {
    return reinterpret_cast<const JointPvtConfig*>(
               &_JointPvtConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(JointPvtConfig& a, JointPvtConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(JointPvtConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointPvtConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JointPvtConfig* New() const final {
    return CreateMaybeMessage<JointPvtConfig>(nullptr);
  }

  JointPvtConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JointPvtConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JointPvtConfig& from);
  void MergeFrom(const JointPvtConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JointPvtConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.JointPvtConfig";
  }
  protected:
  explicit JointPvtConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kLimitMapFieldNumber = 3,
    kPidConfigMapFieldNumber = 4,
    kFilterConfigMapFieldNumber = 5,
    kCtrlImplFieldNumber = 1,
    kDynamicsConfigFieldNumber = 6,
    kCtrlModeFieldNumber = 2,
  };
  // map<string, .galbot.singorix_proto.JointLimits> limit_map = 3;
  int limit_map_size() const;
  private:
  int _internal_limit_map_size() const;
  public:
  void clear_limit_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >&
      _internal_limit_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >*
      _internal_mutable_limit_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >&
      limit_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >*
      mutable_limit_map();

  // map<string, .galbot.singorix_proto.PIDConfig> pid_config_map = 4;
  int pid_config_map_size() const;
  private:
  int _internal_pid_config_map_size() const;
  public:
  void clear_pid_config_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >&
      _internal_pid_config_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >*
      _internal_mutable_pid_config_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >&
      pid_config_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >*
      mutable_pid_config_map();

  // map<string, .galbot.singorix_proto.FilterConfig> filter_config_map = 5;
  int filter_config_map_size() const;
  private:
  int _internal_filter_config_map_size() const;
  public:
  void clear_filter_config_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >&
      _internal_filter_config_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >*
      _internal_mutable_filter_config_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >&
      filter_config_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >*
      mutable_filter_config_map();

  // string ctrl_impl = 1;
  void clear_ctrl_impl();
  const std::string& ctrl_impl() const;
  void set_ctrl_impl(const std::string& value);
  void set_ctrl_impl(std::string&& value);
  void set_ctrl_impl(const char* value);
  void set_ctrl_impl(const char* value, size_t size);
  std::string* mutable_ctrl_impl();
  std::string* release_ctrl_impl();
  void set_allocated_ctrl_impl(std::string* ctrl_impl);
  private:
  const std::string& _internal_ctrl_impl() const;
  void _internal_set_ctrl_impl(const std::string& value);
  std::string* _internal_mutable_ctrl_impl();
  public:

  // .galbot.singorix_proto.DynamicsConfig dynamics_config = 6;
  bool has_dynamics_config() const;
  private:
  bool _internal_has_dynamics_config() const;
  public:
  void clear_dynamics_config();
  const ::galbot::singorix_proto::DynamicsConfig& dynamics_config() const;
  ::galbot::singorix_proto::DynamicsConfig* release_dynamics_config();
  ::galbot::singorix_proto::DynamicsConfig* mutable_dynamics_config();
  void set_allocated_dynamics_config(::galbot::singorix_proto::DynamicsConfig* dynamics_config);
  private:
  const ::galbot::singorix_proto::DynamicsConfig& _internal_dynamics_config() const;
  ::galbot::singorix_proto::DynamicsConfig* _internal_mutable_dynamics_config();
  public:
  void unsafe_arena_set_allocated_dynamics_config(
      ::galbot::singorix_proto::DynamicsConfig* dynamics_config);
  ::galbot::singorix_proto::DynamicsConfig* unsafe_arena_release_dynamics_config();

  // int32 ctrl_mode = 2;
  void clear_ctrl_mode();
  ::PROTOBUF_NAMESPACE_ID::int32 ctrl_mode() const;
  void set_ctrl_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ctrl_mode() const;
  void _internal_set_ctrl_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.JointPvtConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JointPvtConfig_LimitMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::JointLimits,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> limit_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JointPvtConfig_PidConfigMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::PIDConfig,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> pid_config_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JointPvtConfig_FilterConfigMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::FilterConfig,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> filter_config_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ctrl_impl_;
  ::galbot::singorix_proto::DynamicsConfig* dynamics_config_;
  ::PROTOBUF_NAMESPACE_ID::int32 ctrl_mode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::JointPvtConfig,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::JointPvtConfig,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse();
  explicit SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse& other);
  static const SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse*>(&_SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.SingoriXControlConfig.JointPvtConfigMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[10];
  }

  public:
};

// -------------------------------------------------------------------

class SingoriXControlConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.SingoriXControlConfig) */ {
 public:
  inline SingoriXControlConfig() : SingoriXControlConfig(nullptr) {}
  virtual ~SingoriXControlConfig();

  SingoriXControlConfig(const SingoriXControlConfig& from);
  SingoriXControlConfig(SingoriXControlConfig&& from) noexcept
    : SingoriXControlConfig() {
    *this = ::std::move(from);
  }

  inline SingoriXControlConfig& operator=(const SingoriXControlConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline SingoriXControlConfig& operator=(SingoriXControlConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SingoriXControlConfig& default_instance();

  static inline const SingoriXControlConfig* internal_default_instance() {
    return reinterpret_cast<const SingoriXControlConfig*>(
               &_SingoriXControlConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  friend void swap(SingoriXControlConfig& a, SingoriXControlConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(SingoriXControlConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SingoriXControlConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SingoriXControlConfig* New() const final {
    return CreateMaybeMessage<SingoriXControlConfig>(nullptr);
  }

  SingoriXControlConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SingoriXControlConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SingoriXControlConfig& from);
  void MergeFrom(const SingoriXControlConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SingoriXControlConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.SingoriXControlConfig";
  }
  protected:
  explicit SingoriXControlConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kJointPvtConfigMapFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // map<string, .galbot.singorix_proto.JointPvtConfig> joint_pvt_config_map = 2;
  int joint_pvt_config_map_size() const;
  private:
  int _internal_joint_pvt_config_map_size() const;
  public:
  void clear_joint_pvt_config_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >&
      _internal_joint_pvt_config_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >*
      _internal_mutable_joint_pvt_config_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >&
      joint_pvt_config_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >*
      mutable_joint_pvt_config_map();

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.SingoriXControlConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      SingoriXControlConfig_JointPvtConfigMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::JointPvtConfig,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> joint_pvt_config_map_;
  ::galbot::core_proto::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JointLimits

// double position_min = 1;
inline void JointLimits::clear_position_min() {
  position_min_ = 0;
}
inline double JointLimits::_internal_position_min() const {
  return position_min_;
}
inline double JointLimits::position_min() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.position_min)
  return _internal_position_min();
}
inline void JointLimits::_internal_set_position_min(double value) {
  
  position_min_ = value;
}
inline void JointLimits::set_position_min(double value) {
  _internal_set_position_min(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.position_min)
}

// double position_max = 2;
inline void JointLimits::clear_position_max() {
  position_max_ = 0;
}
inline double JointLimits::_internal_position_max() const {
  return position_max_;
}
inline double JointLimits::position_max() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.position_max)
  return _internal_position_max();
}
inline void JointLimits::_internal_set_position_max(double value) {
  
  position_max_ = value;
}
inline void JointLimits::set_position_max(double value) {
  _internal_set_position_max(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.position_max)
}

// double velocity_limit = 3;
inline void JointLimits::clear_velocity_limit() {
  velocity_limit_ = 0;
}
inline double JointLimits::_internal_velocity_limit() const {
  return velocity_limit_;
}
inline double JointLimits::velocity_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.velocity_limit)
  return _internal_velocity_limit();
}
inline void JointLimits::_internal_set_velocity_limit(double value) {
  
  velocity_limit_ = value;
}
inline void JointLimits::set_velocity_limit(double value) {
  _internal_set_velocity_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.velocity_limit)
}

// double acceleration_limit = 4;
inline void JointLimits::clear_acceleration_limit() {
  acceleration_limit_ = 0;
}
inline double JointLimits::_internal_acceleration_limit() const {
  return acceleration_limit_;
}
inline double JointLimits::acceleration_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.acceleration_limit)
  return _internal_acceleration_limit();
}
inline void JointLimits::_internal_set_acceleration_limit(double value) {
  
  acceleration_limit_ = value;
}
inline void JointLimits::set_acceleration_limit(double value) {
  _internal_set_acceleration_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.acceleration_limit)
}

// double jerk_limit = 5;
inline void JointLimits::clear_jerk_limit() {
  jerk_limit_ = 0;
}
inline double JointLimits::_internal_jerk_limit() const {
  return jerk_limit_;
}
inline double JointLimits::jerk_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.jerk_limit)
  return _internal_jerk_limit();
}
inline void JointLimits::_internal_set_jerk_limit(double value) {
  
  jerk_limit_ = value;
}
inline void JointLimits::set_jerk_limit(double value) {
  _internal_set_jerk_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.jerk_limit)
}

// double snap_limit = 6;
inline void JointLimits::clear_snap_limit() {
  snap_limit_ = 0;
}
inline double JointLimits::_internal_snap_limit() const {
  return snap_limit_;
}
inline double JointLimits::snap_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.snap_limit)
  return _internal_snap_limit();
}
inline void JointLimits::_internal_set_snap_limit(double value) {
  
  snap_limit_ = value;
}
inline void JointLimits::set_snap_limit(double value) {
  _internal_set_snap_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.snap_limit)
}

// double effort_limit = 7;
inline void JointLimits::clear_effort_limit() {
  effort_limit_ = 0;
}
inline double JointLimits::_internal_effort_limit() const {
  return effort_limit_;
}
inline double JointLimits::effort_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.effort_limit)
  return _internal_effort_limit();
}
inline void JointLimits::_internal_set_effort_limit(double value) {
  
  effort_limit_ = value;
}
inline void JointLimits::set_effort_limit(double value) {
  _internal_set_effort_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.effort_limit)
}

// double current_limit = 8;
inline void JointLimits::clear_current_limit() {
  current_limit_ = 0;
}
inline double JointLimits::_internal_current_limit() const {
  return current_limit_;
}
inline double JointLimits::current_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointLimits.current_limit)
  return _internal_current_limit();
}
inline void JointLimits::_internal_set_current_limit(double value) {
  
  current_limit_ = value;
}
inline void JointLimits::set_current_limit(double value) {
  _internal_set_current_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointLimits.current_limit)
}

// -------------------------------------------------------------------

// PIDConfig

// double kp = 1;
inline void PIDConfig::clear_kp() {
  kp_ = 0;
}
inline double PIDConfig::_internal_kp() const {
  return kp_;
}
inline double PIDConfig::kp() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.PIDConfig.kp)
  return _internal_kp();
}
inline void PIDConfig::_internal_set_kp(double value) {
  
  kp_ = value;
}
inline void PIDConfig::set_kp(double value) {
  _internal_set_kp(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.PIDConfig.kp)
}

// double ki = 2;
inline void PIDConfig::clear_ki() {
  ki_ = 0;
}
inline double PIDConfig::_internal_ki() const {
  return ki_;
}
inline double PIDConfig::ki() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.PIDConfig.ki)
  return _internal_ki();
}
inline void PIDConfig::_internal_set_ki(double value) {
  
  ki_ = value;
}
inline void PIDConfig::set_ki(double value) {
  _internal_set_ki(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.PIDConfig.ki)
}

// double kd = 3;
inline void PIDConfig::clear_kd() {
  kd_ = 0;
}
inline double PIDConfig::_internal_kd() const {
  return kd_;
}
inline double PIDConfig::kd() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.PIDConfig.kd)
  return _internal_kd();
}
inline void PIDConfig::_internal_set_kd(double value) {
  
  kd_ = value;
}
inline void PIDConfig::set_kd(double value) {
  _internal_set_kd(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.PIDConfig.kd)
}

// double i_limit = 4;
inline void PIDConfig::clear_i_limit() {
  i_limit_ = 0;
}
inline double PIDConfig::_internal_i_limit() const {
  return i_limit_;
}
inline double PIDConfig::i_limit() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.PIDConfig.i_limit)
  return _internal_i_limit();
}
inline void PIDConfig::_internal_set_i_limit(double value) {
  
  i_limit_ = value;
}
inline void PIDConfig::set_i_limit(double value) {
  _internal_set_i_limit(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.PIDConfig.i_limit)
}

// double i_sep_thr = 5;
inline void PIDConfig::clear_i_sep_thr() {
  i_sep_thr_ = 0;
}
inline double PIDConfig::_internal_i_sep_thr() const {
  return i_sep_thr_;
}
inline double PIDConfig::i_sep_thr() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.PIDConfig.i_sep_thr)
  return _internal_i_sep_thr();
}
inline void PIDConfig::_internal_set_i_sep_thr(double value) {
  
  i_sep_thr_ = value;
}
inline void PIDConfig::set_i_sep_thr(double value) {
  _internal_set_i_sep_thr(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.PIDConfig.i_sep_thr)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// FilterConfig

// string filter_impl = 1;
inline void FilterConfig::clear_filter_impl() {
  filter_impl_.ClearToEmpty();
}
inline const std::string& FilterConfig::filter_impl() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.FilterConfig.filter_impl)
  return _internal_filter_impl();
}
inline void FilterConfig::set_filter_impl(const std::string& value) {
  _internal_set_filter_impl(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.FilterConfig.filter_impl)
}
inline std::string* FilterConfig::mutable_filter_impl() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.FilterConfig.filter_impl)
  return _internal_mutable_filter_impl();
}
inline const std::string& FilterConfig::_internal_filter_impl() const {
  return filter_impl_.Get();
}
inline void FilterConfig::_internal_set_filter_impl(const std::string& value) {
  
  filter_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FilterConfig::set_filter_impl(std::string&& value) {
  
  filter_impl_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.FilterConfig.filter_impl)
}
inline void FilterConfig::set_filter_impl(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filter_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.FilterConfig.filter_impl)
}
inline void FilterConfig::set_filter_impl(const char* value,
    size_t size) {
  
  filter_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.FilterConfig.filter_impl)
}
inline std::string* FilterConfig::_internal_mutable_filter_impl() {
  
  return filter_impl_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FilterConfig::release_filter_impl() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.FilterConfig.filter_impl)
  return filter_impl_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FilterConfig::set_allocated_filter_impl(std::string* filter_impl) {
  if (filter_impl != nullptr) {
    
  } else {
    
  }
  filter_impl_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filter_impl,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.FilterConfig.filter_impl)
}

// double cutoff_frequency = 2;
inline void FilterConfig::clear_cutoff_frequency() {
  cutoff_frequency_ = 0;
}
inline double FilterConfig::_internal_cutoff_frequency() const {
  return cutoff_frequency_;
}
inline double FilterConfig::cutoff_frequency() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.FilterConfig.cutoff_frequency)
  return _internal_cutoff_frequency();
}
inline void FilterConfig::_internal_set_cutoff_frequency(double value) {
  
  cutoff_frequency_ = value;
}
inline void FilterConfig::set_cutoff_frequency(double value) {
  _internal_set_cutoff_frequency(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.FilterConfig.cutoff_frequency)
}

// double sampling_frequency = 3;
inline void FilterConfig::clear_sampling_frequency() {
  sampling_frequency_ = 0;
}
inline double FilterConfig::_internal_sampling_frequency() const {
  return sampling_frequency_;
}
inline double FilterConfig::sampling_frequency() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.FilterConfig.sampling_frequency)
  return _internal_sampling_frequency();
}
inline void FilterConfig::_internal_set_sampling_frequency(double value) {
  
  sampling_frequency_ = value;
}
inline void FilterConfig::set_sampling_frequency(double value) {
  _internal_set_sampling_frequency(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.FilterConfig.sampling_frequency)
}

// map<string, .galbot.core_proto.Value> param_map = 4;
inline int FilterConfig::_internal_param_map_size() const {
  return param_map_.size();
}
inline int FilterConfig::param_map_size() const {
  return _internal_param_map_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
FilterConfig::_internal_param_map() const {
  return param_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
FilterConfig::param_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.FilterConfig.param_map)
  return _internal_param_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
FilterConfig::_internal_mutable_param_map() {
  return param_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
FilterConfig::mutable_param_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.FilterConfig.param_map)
  return _internal_mutable_param_map();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DynamicsConfig

// string dynamics_impl = 1;
inline void DynamicsConfig::clear_dynamics_impl() {
  dynamics_impl_.ClearToEmpty();
}
inline const std::string& DynamicsConfig::dynamics_impl() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
  return _internal_dynamics_impl();
}
inline void DynamicsConfig::set_dynamics_impl(const std::string& value) {
  _internal_set_dynamics_impl(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
}
inline std::string* DynamicsConfig::mutable_dynamics_impl() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
  return _internal_mutable_dynamics_impl();
}
inline const std::string& DynamicsConfig::_internal_dynamics_impl() const {
  return dynamics_impl_.Get();
}
inline void DynamicsConfig::_internal_set_dynamics_impl(const std::string& value) {
  
  dynamics_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void DynamicsConfig::set_dynamics_impl(std::string&& value) {
  
  dynamics_impl_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
}
inline void DynamicsConfig::set_dynamics_impl(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  dynamics_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
}
inline void DynamicsConfig::set_dynamics_impl(const char* value,
    size_t size) {
  
  dynamics_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
}
inline std::string* DynamicsConfig::_internal_mutable_dynamics_impl() {
  
  return dynamics_impl_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* DynamicsConfig::release_dynamics_impl() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
  return dynamics_impl_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void DynamicsConfig::set_allocated_dynamics_impl(std::string* dynamics_impl) {
  if (dynamics_impl != nullptr) {
    
  } else {
    
  }
  dynamics_impl_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), dynamics_impl,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.DynamicsConfig.dynamics_impl)
}

// map<string, .galbot.core_proto.Value> param_map = 2;
inline int DynamicsConfig::_internal_param_map_size() const {
  return param_map_.size();
}
inline int DynamicsConfig::param_map_size() const {
  return _internal_param_map_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
DynamicsConfig::_internal_param_map() const {
  return param_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >&
DynamicsConfig::param_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.DynamicsConfig.param_map)
  return _internal_param_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
DynamicsConfig::_internal_mutable_param_map() {
  return param_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::core_proto::Value >*
DynamicsConfig::mutable_param_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.DynamicsConfig.param_map)
  return _internal_mutable_param_map();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// JointPvtConfig

// string ctrl_impl = 1;
inline void JointPvtConfig::clear_ctrl_impl() {
  ctrl_impl_.ClearToEmpty();
}
inline const std::string& JointPvtConfig::ctrl_impl() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
  return _internal_ctrl_impl();
}
inline void JointPvtConfig::set_ctrl_impl(const std::string& value) {
  _internal_set_ctrl_impl(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
}
inline std::string* JointPvtConfig::mutable_ctrl_impl() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
  return _internal_mutable_ctrl_impl();
}
inline const std::string& JointPvtConfig::_internal_ctrl_impl() const {
  return ctrl_impl_.Get();
}
inline void JointPvtConfig::_internal_set_ctrl_impl(const std::string& value) {
  
  ctrl_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void JointPvtConfig::set_ctrl_impl(std::string&& value) {
  
  ctrl_impl_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
}
inline void JointPvtConfig::set_ctrl_impl(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ctrl_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
}
inline void JointPvtConfig::set_ctrl_impl(const char* value,
    size_t size) {
  
  ctrl_impl_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
}
inline std::string* JointPvtConfig::_internal_mutable_ctrl_impl() {
  
  return ctrl_impl_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* JointPvtConfig::release_ctrl_impl() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
  return ctrl_impl_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void JointPvtConfig::set_allocated_ctrl_impl(std::string* ctrl_impl) {
  if (ctrl_impl != nullptr) {
    
  } else {
    
  }
  ctrl_impl_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ctrl_impl,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.JointPvtConfig.ctrl_impl)
}

// int32 ctrl_mode = 2;
inline void JointPvtConfig::clear_ctrl_mode() {
  ctrl_mode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 JointPvtConfig::_internal_ctrl_mode() const {
  return ctrl_mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 JointPvtConfig::ctrl_mode() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointPvtConfig.ctrl_mode)
  return _internal_ctrl_mode();
}
inline void JointPvtConfig::_internal_set_ctrl_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  ctrl_mode_ = value;
}
inline void JointPvtConfig::set_ctrl_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ctrl_mode(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.JointPvtConfig.ctrl_mode)
}

// map<string, .galbot.singorix_proto.JointLimits> limit_map = 3;
inline int JointPvtConfig::_internal_limit_map_size() const {
  return limit_map_.size();
}
inline int JointPvtConfig::limit_map_size() const {
  return _internal_limit_map_size();
}
inline void JointPvtConfig::clear_limit_map() {
  limit_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >&
JointPvtConfig::_internal_limit_map() const {
  return limit_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >&
JointPvtConfig::limit_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.JointPvtConfig.limit_map)
  return _internal_limit_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >*
JointPvtConfig::_internal_mutable_limit_map() {
  return limit_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointLimits >*
JointPvtConfig::mutable_limit_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.JointPvtConfig.limit_map)
  return _internal_mutable_limit_map();
}

// map<string, .galbot.singorix_proto.PIDConfig> pid_config_map = 4;
inline int JointPvtConfig::_internal_pid_config_map_size() const {
  return pid_config_map_.size();
}
inline int JointPvtConfig::pid_config_map_size() const {
  return _internal_pid_config_map_size();
}
inline void JointPvtConfig::clear_pid_config_map() {
  pid_config_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >&
JointPvtConfig::_internal_pid_config_map() const {
  return pid_config_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >&
JointPvtConfig::pid_config_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.JointPvtConfig.pid_config_map)
  return _internal_pid_config_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >*
JointPvtConfig::_internal_mutable_pid_config_map() {
  return pid_config_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::PIDConfig >*
JointPvtConfig::mutable_pid_config_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.JointPvtConfig.pid_config_map)
  return _internal_mutable_pid_config_map();
}

// map<string, .galbot.singorix_proto.FilterConfig> filter_config_map = 5;
inline int JointPvtConfig::_internal_filter_config_map_size() const {
  return filter_config_map_.size();
}
inline int JointPvtConfig::filter_config_map_size() const {
  return _internal_filter_config_map_size();
}
inline void JointPvtConfig::clear_filter_config_map() {
  filter_config_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >&
JointPvtConfig::_internal_filter_config_map() const {
  return filter_config_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >&
JointPvtConfig::filter_config_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.JointPvtConfig.filter_config_map)
  return _internal_filter_config_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >*
JointPvtConfig::_internal_mutable_filter_config_map() {
  return filter_config_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::FilterConfig >*
JointPvtConfig::mutable_filter_config_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.JointPvtConfig.filter_config_map)
  return _internal_mutable_filter_config_map();
}

// .galbot.singorix_proto.DynamicsConfig dynamics_config = 6;
inline bool JointPvtConfig::_internal_has_dynamics_config() const {
  return this != internal_default_instance() && dynamics_config_ != nullptr;
}
inline bool JointPvtConfig::has_dynamics_config() const {
  return _internal_has_dynamics_config();
}
inline void JointPvtConfig::clear_dynamics_config() {
  if (GetArena() == nullptr && dynamics_config_ != nullptr) {
    delete dynamics_config_;
  }
  dynamics_config_ = nullptr;
}
inline const ::galbot::singorix_proto::DynamicsConfig& JointPvtConfig::_internal_dynamics_config() const {
  const ::galbot::singorix_proto::DynamicsConfig* p = dynamics_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::singorix_proto::DynamicsConfig&>(
      ::galbot::singorix_proto::_DynamicsConfig_default_instance_);
}
inline const ::galbot::singorix_proto::DynamicsConfig& JointPvtConfig::dynamics_config() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.JointPvtConfig.dynamics_config)
  return _internal_dynamics_config();
}
inline void JointPvtConfig::unsafe_arena_set_allocated_dynamics_config(
    ::galbot::singorix_proto::DynamicsConfig* dynamics_config) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(dynamics_config_);
  }
  dynamics_config_ = dynamics_config;
  if (dynamics_config) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.JointPvtConfig.dynamics_config)
}
inline ::galbot::singorix_proto::DynamicsConfig* JointPvtConfig::release_dynamics_config() {
  
  ::galbot::singorix_proto::DynamicsConfig* temp = dynamics_config_;
  dynamics_config_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::singorix_proto::DynamicsConfig* JointPvtConfig::unsafe_arena_release_dynamics_config() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.JointPvtConfig.dynamics_config)
  
  ::galbot::singorix_proto::DynamicsConfig* temp = dynamics_config_;
  dynamics_config_ = nullptr;
  return temp;
}
inline ::galbot::singorix_proto::DynamicsConfig* JointPvtConfig::_internal_mutable_dynamics_config() {
  
  if (dynamics_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::singorix_proto::DynamicsConfig>(GetArena());
    dynamics_config_ = p;
  }
  return dynamics_config_;
}
inline ::galbot::singorix_proto::DynamicsConfig* JointPvtConfig::mutable_dynamics_config() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.JointPvtConfig.dynamics_config)
  return _internal_mutable_dynamics_config();
}
inline void JointPvtConfig::set_allocated_dynamics_config(::galbot::singorix_proto::DynamicsConfig* dynamics_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete dynamics_config_;
  }
  if (dynamics_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(dynamics_config);
    if (message_arena != submessage_arena) {
      dynamics_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dynamics_config, submessage_arena);
    }
    
  } else {
    
  }
  dynamics_config_ = dynamics_config;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.JointPvtConfig.dynamics_config)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SingoriXControlConfig

// .galbot.core_proto.Header header = 1;
inline bool SingoriXControlConfig::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool SingoriXControlConfig::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& SingoriXControlConfig::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& SingoriXControlConfig::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.SingoriXControlConfig.header)
  return _internal_header();
}
inline void SingoriXControlConfig::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.SingoriXControlConfig.header)
}
inline ::galbot::core_proto::Header* SingoriXControlConfig::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* SingoriXControlConfig::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.SingoriXControlConfig.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* SingoriXControlConfig::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* SingoriXControlConfig::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.SingoriXControlConfig.header)
  return _internal_mutable_header();
}
inline void SingoriXControlConfig::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.SingoriXControlConfig.header)
}

// map<string, .galbot.singorix_proto.JointPvtConfig> joint_pvt_config_map = 2;
inline int SingoriXControlConfig::_internal_joint_pvt_config_map_size() const {
  return joint_pvt_config_map_.size();
}
inline int SingoriXControlConfig::joint_pvt_config_map_size() const {
  return _internal_joint_pvt_config_map_size();
}
inline void SingoriXControlConfig::clear_joint_pvt_config_map() {
  joint_pvt_config_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >&
SingoriXControlConfig::_internal_joint_pvt_config_map() const {
  return joint_pvt_config_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >&
SingoriXControlConfig::joint_pvt_config_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.SingoriXControlConfig.joint_pvt_config_map)
  return _internal_joint_pvt_config_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >*
SingoriXControlConfig::_internal_mutable_joint_pvt_config_map() {
  return joint_pvt_config_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::JointPvtConfig >*
SingoriXControlConfig::mutable_joint_pvt_config_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.SingoriXControlConfig.joint_pvt_config_map)
  return _internal_mutable_joint_pvt_config_map();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace singorix_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fcontrol_5fconfig_2eproto
