// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/singorix_proto/singorix_motor_statistics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto;
namespace galbot {
namespace singorix_proto {
class GroupMotorStatistics;
class GroupMotorStatisticsDefaultTypeInternal;
extern GroupMotorStatisticsDefaultTypeInternal _GroupMotorStatistics_default_instance_;
class MotorStatistics;
class MotorStatisticsDefaultTypeInternal;
extern MotorStatisticsDefaultTypeInternal _MotorStatistics_default_instance_;
class MotorStatisticsReport;
class MotorStatisticsReportDefaultTypeInternal;
extern MotorStatisticsReportDefaultTypeInternal _MotorStatisticsReport_default_instance_;
class MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse;
class MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUseDefaultTypeInternal;
extern MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUseDefaultTypeInternal _MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse_default_instance_;
class Nx1MotorStatistics;
class Nx1MotorStatisticsDefaultTypeInternal;
extern Nx1MotorStatisticsDefaultTypeInternal _Nx1MotorStatistics_default_instance_;
class Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse;
class Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUseDefaultTypeInternal;
extern Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUseDefaultTypeInternal _Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse_default_instance_;
}  // namespace singorix_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::singorix_proto::GroupMotorStatistics* Arena::CreateMaybeMessage<::galbot::singorix_proto::GroupMotorStatistics>(Arena*);
template<> ::galbot::singorix_proto::MotorStatistics* Arena::CreateMaybeMessage<::galbot::singorix_proto::MotorStatistics>(Arena*);
template<> ::galbot::singorix_proto::MotorStatisticsReport* Arena::CreateMaybeMessage<::galbot::singorix_proto::MotorStatisticsReport>(Arena*);
template<> ::galbot::singorix_proto::MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse>(Arena*);
template<> ::galbot::singorix_proto::Nx1MotorStatistics* Arena::CreateMaybeMessage<::galbot::singorix_proto::Nx1MotorStatistics>(Arena*);
template<> ::galbot::singorix_proto::Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse* Arena::CreateMaybeMessage<::galbot::singorix_proto::Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace singorix_proto {

// ===================================================================

class MotorStatistics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.MotorStatistics) */ {
 public:
  inline MotorStatistics() : MotorStatistics(nullptr) {}
  virtual ~MotorStatistics();

  MotorStatistics(const MotorStatistics& from);
  MotorStatistics(MotorStatistics&& from) noexcept
    : MotorStatistics() {
    *this = ::std::move(from);
  }

  inline MotorStatistics& operator=(const MotorStatistics& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorStatistics& operator=(MotorStatistics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorStatistics& default_instance();

  static inline const MotorStatistics* internal_default_instance() {
    return reinterpret_cast<const MotorStatistics*>(
               &_MotorStatistics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MotorStatistics& a, MotorStatistics& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorStatistics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorStatistics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorStatistics* New() const final {
    return CreateMaybeMessage<MotorStatistics>(nullptr);
  }

  MotorStatistics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorStatistics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorStatistics& from);
  void MergeFrom(const MotorStatistics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorStatistics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.MotorStatistics";
  }
  protected:
  explicit MotorStatistics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSourceNameFieldNumber = 11,
    kSourceTypeFieldNumber = 13,
    kTxCountFieldNumber = 1,
    kRxCountFieldNumber = 2,
    kTxErrCountFieldNumber = 3,
    kRxErrCountFieldNumber = 4,
    kDisconnCountFieldNumber = 5,
    kFrameRateFieldNumber = 6,
    kFailureRateFieldNumber = 7,
    kAvgFrameRateFieldNumber = 8,
    kDurationMsFieldNumber = 10,
    kAvgFailureRateFieldNumber = 9,
    kSourceIdFieldNumber = 12,
  };
  // string source_name = 11;
  void clear_source_name();
  const std::string& source_name() const;
  void set_source_name(const std::string& value);
  void set_source_name(std::string&& value);
  void set_source_name(const char* value);
  void set_source_name(const char* value, size_t size);
  std::string* mutable_source_name();
  std::string* release_source_name();
  void set_allocated_source_name(std::string* source_name);
  private:
  const std::string& _internal_source_name() const;
  void _internal_set_source_name(const std::string& value);
  std::string* _internal_mutable_source_name();
  public:

  // string source_type = 13;
  void clear_source_type();
  const std::string& source_type() const;
  void set_source_type(const std::string& value);
  void set_source_type(std::string&& value);
  void set_source_type(const char* value);
  void set_source_type(const char* value, size_t size);
  std::string* mutable_source_type();
  std::string* release_source_type();
  void set_allocated_source_type(std::string* source_type);
  private:
  const std::string& _internal_source_type() const;
  void _internal_set_source_type(const std::string& value);
  std::string* _internal_mutable_source_type();
  public:

  // uint64 tx_count = 1;
  void clear_tx_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 tx_count() const;
  void set_tx_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_tx_count() const;
  void _internal_set_tx_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 rx_count = 2;
  void clear_rx_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 rx_count() const;
  void set_rx_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_rx_count() const;
  void _internal_set_rx_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 tx_err_count = 3;
  void clear_tx_err_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 tx_err_count() const;
  void set_tx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_tx_err_count() const;
  void _internal_set_tx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 rx_err_count = 4;
  void clear_rx_err_count();
  ::PROTOBUF_NAMESPACE_ID::uint64 rx_err_count() const;
  void set_rx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_rx_err_count() const;
  void _internal_set_rx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 disconn_count = 5;
  void clear_disconn_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 disconn_count() const;
  void set_disconn_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_disconn_count() const;
  void _internal_set_disconn_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float frame_rate = 6;
  void clear_frame_rate();
  float frame_rate() const;
  void set_frame_rate(float value);
  private:
  float _internal_frame_rate() const;
  void _internal_set_frame_rate(float value);
  public:

  // float failure_rate = 7;
  void clear_failure_rate();
  float failure_rate() const;
  void set_failure_rate(float value);
  private:
  float _internal_failure_rate() const;
  void _internal_set_failure_rate(float value);
  public:

  // float avg_frame_rate = 8;
  void clear_avg_frame_rate();
  float avg_frame_rate() const;
  void set_avg_frame_rate(float value);
  private:
  float _internal_avg_frame_rate() const;
  void _internal_set_avg_frame_rate(float value);
  public:

  // uint64 duration_ms = 10;
  void clear_duration_ms();
  ::PROTOBUF_NAMESPACE_ID::uint64 duration_ms() const;
  void set_duration_ms(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_duration_ms() const;
  void _internal_set_duration_ms(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // float avg_failure_rate = 9;
  void clear_avg_failure_rate();
  float avg_failure_rate() const;
  void set_avg_failure_rate(float value);
  private:
  float _internal_avg_failure_rate() const;
  void _internal_set_avg_failure_rate(float value);
  public:

  // uint32 source_id = 12;
  void clear_source_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 source_id() const;
  void set_source_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_source_id() const;
  void _internal_set_source_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.MotorStatistics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_type_;
  ::PROTOBUF_NAMESPACE_ID::uint64 tx_count_;
  ::PROTOBUF_NAMESPACE_ID::uint64 rx_count_;
  ::PROTOBUF_NAMESPACE_ID::uint64 tx_err_count_;
  ::PROTOBUF_NAMESPACE_ID::uint64 rx_err_count_;
  ::PROTOBUF_NAMESPACE_ID::uint32 disconn_count_;
  float frame_rate_;
  float failure_rate_;
  float avg_frame_rate_;
  ::PROTOBUF_NAMESPACE_ID::uint64 duration_ms_;
  float avg_failure_rate_;
  ::PROTOBUF_NAMESPACE_ID::uint32 source_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class GroupMotorStatistics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.GroupMotorStatistics) */ {
 public:
  inline GroupMotorStatistics() : GroupMotorStatistics(nullptr) {}
  virtual ~GroupMotorStatistics();

  GroupMotorStatistics(const GroupMotorStatistics& from);
  GroupMotorStatistics(GroupMotorStatistics&& from) noexcept
    : GroupMotorStatistics() {
    *this = ::std::move(from);
  }

  inline GroupMotorStatistics& operator=(const GroupMotorStatistics& from) {
    CopyFrom(from);
    return *this;
  }
  inline GroupMotorStatistics& operator=(GroupMotorStatistics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GroupMotorStatistics& default_instance();

  static inline const GroupMotorStatistics* internal_default_instance() {
    return reinterpret_cast<const GroupMotorStatistics*>(
               &_GroupMotorStatistics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GroupMotorStatistics& a, GroupMotorStatistics& b) {
    a.Swap(&b);
  }
  inline void Swap(GroupMotorStatistics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GroupMotorStatistics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GroupMotorStatistics* New() const final {
    return CreateMaybeMessage<GroupMotorStatistics>(nullptr);
  }

  GroupMotorStatistics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GroupMotorStatistics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GroupMotorStatistics& from);
  void MergeFrom(const GroupMotorStatistics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GroupMotorStatistics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.GroupMotorStatistics";
  }
  protected:
  explicit GroupMotorStatistics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJointNamesFieldNumber = 3,
    kStatisticsFieldNumber = 4,
    kSourceNamesFieldNumber = 5,
    kSourceIdsFieldNumber = 6,
    kGroupNameFieldNumber = 2,
    kInterfaceNameFieldNumber = 7,
    kDeviceNameFieldNumber = 8,
    kHeaderFieldNumber = 1,
  };
  // repeated string joint_names = 3;
  int joint_names_size() const;
  private:
  int _internal_joint_names_size() const;
  public:
  void clear_joint_names();
  const std::string& joint_names(int index) const;
  std::string* mutable_joint_names(int index);
  void set_joint_names(int index, const std::string& value);
  void set_joint_names(int index, std::string&& value);
  void set_joint_names(int index, const char* value);
  void set_joint_names(int index, const char* value, size_t size);
  std::string* add_joint_names();
  void add_joint_names(const std::string& value);
  void add_joint_names(std::string&& value);
  void add_joint_names(const char* value);
  void add_joint_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& joint_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_joint_names();
  private:
  const std::string& _internal_joint_names(int index) const;
  std::string* _internal_add_joint_names();
  public:

  // repeated .galbot.singorix_proto.MotorStatistics statistics = 4;
  int statistics_size() const;
  private:
  int _internal_statistics_size() const;
  public:
  void clear_statistics();
  ::galbot::singorix_proto::MotorStatistics* mutable_statistics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::singorix_proto::MotorStatistics >*
      mutable_statistics();
  private:
  const ::galbot::singorix_proto::MotorStatistics& _internal_statistics(int index) const;
  ::galbot::singorix_proto::MotorStatistics* _internal_add_statistics();
  public:
  const ::galbot::singorix_proto::MotorStatistics& statistics(int index) const;
  ::galbot::singorix_proto::MotorStatistics* add_statistics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::singorix_proto::MotorStatistics >&
      statistics() const;

  // repeated string source_names = 5;
  int source_names_size() const;
  private:
  int _internal_source_names_size() const;
  public:
  void clear_source_names();
  const std::string& source_names(int index) const;
  std::string* mutable_source_names(int index);
  void set_source_names(int index, const std::string& value);
  void set_source_names(int index, std::string&& value);
  void set_source_names(int index, const char* value);
  void set_source_names(int index, const char* value, size_t size);
  std::string* add_source_names();
  void add_source_names(const std::string& value);
  void add_source_names(std::string&& value);
  void add_source_names(const char* value);
  void add_source_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& source_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_source_names();
  private:
  const std::string& _internal_source_names(int index) const;
  std::string* _internal_add_source_names();
  public:

  // repeated uint32 source_ids = 6;
  int source_ids_size() const;
  private:
  int _internal_source_ids_size() const;
  public:
  void clear_source_ids();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_source_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_source_ids() const;
  void _internal_add_source_ids(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_source_ids();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 source_ids(int index) const;
  void set_source_ids(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_source_ids(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      source_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_source_ids();

  // string group_name = 2;
  void clear_group_name();
  const std::string& group_name() const;
  void set_group_name(const std::string& value);
  void set_group_name(std::string&& value);
  void set_group_name(const char* value);
  void set_group_name(const char* value, size_t size);
  std::string* mutable_group_name();
  std::string* release_group_name();
  void set_allocated_group_name(std::string* group_name);
  private:
  const std::string& _internal_group_name() const;
  void _internal_set_group_name(const std::string& value);
  std::string* _internal_mutable_group_name();
  public:

  // string interface_name = 7;
  void clear_interface_name();
  const std::string& interface_name() const;
  void set_interface_name(const std::string& value);
  void set_interface_name(std::string&& value);
  void set_interface_name(const char* value);
  void set_interface_name(const char* value, size_t size);
  std::string* mutable_interface_name();
  std::string* release_interface_name();
  void set_allocated_interface_name(std::string* interface_name);
  private:
  const std::string& _internal_interface_name() const;
  void _internal_set_interface_name(const std::string& value);
  std::string* _internal_mutable_interface_name();
  public:

  // string device_name = 8;
  void clear_device_name();
  const std::string& device_name() const;
  void set_device_name(const std::string& value);
  void set_device_name(std::string&& value);
  void set_device_name(const char* value);
  void set_device_name(const char* value, size_t size);
  std::string* mutable_device_name();
  std::string* release_device_name();
  void set_allocated_device_name(std::string* device_name);
  private:
  const std::string& _internal_device_name() const;
  void _internal_set_device_name(const std::string& value);
  std::string* _internal_mutable_device_name();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.GroupMotorStatistics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> joint_names_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::singorix_proto::MotorStatistics > statistics_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> source_names_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > source_ids_;
  mutable std::atomic<int> _source_ids_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr group_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr interface_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_name_;
  ::galbot::core_proto::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::GroupMotorStatistics,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::GroupMotorStatistics,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse();
  explicit MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse& other);
  static const MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse*>(&_MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.MotorStatisticsReport.GroupStatisticsMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class MotorStatisticsReport PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.MotorStatisticsReport) */ {
 public:
  inline MotorStatisticsReport() : MotorStatisticsReport(nullptr) {}
  virtual ~MotorStatisticsReport();

  MotorStatisticsReport(const MotorStatisticsReport& from);
  MotorStatisticsReport(MotorStatisticsReport&& from) noexcept
    : MotorStatisticsReport() {
    *this = ::std::move(from);
  }

  inline MotorStatisticsReport& operator=(const MotorStatisticsReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorStatisticsReport& operator=(MotorStatisticsReport&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorStatisticsReport& default_instance();

  static inline const MotorStatisticsReport* internal_default_instance() {
    return reinterpret_cast<const MotorStatisticsReport*>(
               &_MotorStatisticsReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MotorStatisticsReport& a, MotorStatisticsReport& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorStatisticsReport* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorStatisticsReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorStatisticsReport* New() const final {
    return CreateMaybeMessage<MotorStatisticsReport>(nullptr);
  }

  MotorStatisticsReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorStatisticsReport>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorStatisticsReport& from);
  void MergeFrom(const MotorStatisticsReport& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorStatisticsReport* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.MotorStatisticsReport";
  }
  protected:
  explicit MotorStatisticsReport(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kGroupStatisticsMapFieldNumber = 3,
    kRobotModelFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // map<string, .galbot.singorix_proto.GroupMotorStatistics> group_statistics_map = 3;
  int group_statistics_map_size() const;
  private:
  int _internal_group_statistics_map_size() const;
  public:
  void clear_group_statistics_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
      _internal_group_statistics_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
      _internal_mutable_group_statistics_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
      group_statistics_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
      mutable_group_statistics_map();

  // string robot_model = 2;
  void clear_robot_model();
  const std::string& robot_model() const;
  void set_robot_model(const std::string& value);
  void set_robot_model(std::string&& value);
  void set_robot_model(const char* value);
  void set_robot_model(const char* value, size_t size);
  std::string* mutable_robot_model();
  std::string* release_robot_model();
  void set_allocated_robot_model(std::string* robot_model);
  private:
  const std::string& _internal_robot_model() const;
  void _internal_set_robot_model(const std::string& value);
  std::string* _internal_mutable_robot_model();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.MotorStatisticsReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MotorStatisticsReport_GroupStatisticsMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::GroupMotorStatistics,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> group_statistics_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr robot_model_;
  ::galbot::core_proto::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::GroupMotorStatistics,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse, 
    std::string, ::galbot::singorix_proto::GroupMotorStatistics,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse();
  explicit Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse& other);
  static const Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse*>(&_Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "galbot.singorix_proto.Nx1MotorStatistics.GroupStatisticsMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto.file_level_metadata[4];
  }

  public:
};

// -------------------------------------------------------------------

class Nx1MotorStatistics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.Nx1MotorStatistics) */ {
 public:
  inline Nx1MotorStatistics() : Nx1MotorStatistics(nullptr) {}
  virtual ~Nx1MotorStatistics();

  Nx1MotorStatistics(const Nx1MotorStatistics& from);
  Nx1MotorStatistics(Nx1MotorStatistics&& from) noexcept
    : Nx1MotorStatistics() {
    *this = ::std::move(from);
  }

  inline Nx1MotorStatistics& operator=(const Nx1MotorStatistics& from) {
    CopyFrom(from);
    return *this;
  }
  inline Nx1MotorStatistics& operator=(Nx1MotorStatistics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Nx1MotorStatistics& default_instance();

  static inline const Nx1MotorStatistics* internal_default_instance() {
    return reinterpret_cast<const Nx1MotorStatistics*>(
               &_Nx1MotorStatistics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Nx1MotorStatistics& a, Nx1MotorStatistics& b) {
    a.Swap(&b);
  }
  inline void Swap(Nx1MotorStatistics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Nx1MotorStatistics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Nx1MotorStatistics* New() const final {
    return CreateMaybeMessage<Nx1MotorStatistics>(nullptr);
  }

  Nx1MotorStatistics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Nx1MotorStatistics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Nx1MotorStatistics& from);
  void MergeFrom(const Nx1MotorStatistics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Nx1MotorStatistics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.Nx1MotorStatistics";
  }
  protected:
  explicit Nx1MotorStatistics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kGroupStatisticsMapFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // map<string, .galbot.singorix_proto.GroupMotorStatistics> group_statistics_map = 2;
  int group_statistics_map_size() const;
  private:
  int _internal_group_statistics_map_size() const;
  public:
  void clear_group_statistics_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
      _internal_group_statistics_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
      _internal_mutable_group_statistics_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
      group_statistics_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
      mutable_group_statistics_map();

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.Nx1MotorStatistics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Nx1MotorStatistics_GroupStatisticsMapEntry_DoNotUse,
      std::string, ::galbot::singorix_proto::GroupMotorStatistics,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> group_statistics_map_;
  ::galbot::core_proto::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MotorStatistics

// uint64 tx_count = 1;
inline void MotorStatistics::clear_tx_count() {
  tx_count_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::_internal_tx_count() const {
  return tx_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::tx_count() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.tx_count)
  return _internal_tx_count();
}
inline void MotorStatistics::_internal_set_tx_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  tx_count_ = value;
}
inline void MotorStatistics::set_tx_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_tx_count(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.tx_count)
}

// uint64 rx_count = 2;
inline void MotorStatistics::clear_rx_count() {
  rx_count_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::_internal_rx_count() const {
  return rx_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::rx_count() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.rx_count)
  return _internal_rx_count();
}
inline void MotorStatistics::_internal_set_rx_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  rx_count_ = value;
}
inline void MotorStatistics::set_rx_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_rx_count(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.rx_count)
}

// uint64 tx_err_count = 3;
inline void MotorStatistics::clear_tx_err_count() {
  tx_err_count_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::_internal_tx_err_count() const {
  return tx_err_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::tx_err_count() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.tx_err_count)
  return _internal_tx_err_count();
}
inline void MotorStatistics::_internal_set_tx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  tx_err_count_ = value;
}
inline void MotorStatistics::set_tx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_tx_err_count(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.tx_err_count)
}

// uint64 rx_err_count = 4;
inline void MotorStatistics::clear_rx_err_count() {
  rx_err_count_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::_internal_rx_err_count() const {
  return rx_err_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::rx_err_count() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.rx_err_count)
  return _internal_rx_err_count();
}
inline void MotorStatistics::_internal_set_rx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  rx_err_count_ = value;
}
inline void MotorStatistics::set_rx_err_count(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_rx_err_count(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.rx_err_count)
}

// uint32 disconn_count = 5;
inline void MotorStatistics::clear_disconn_count() {
  disconn_count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorStatistics::_internal_disconn_count() const {
  return disconn_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorStatistics::disconn_count() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.disconn_count)
  return _internal_disconn_count();
}
inline void MotorStatistics::_internal_set_disconn_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  disconn_count_ = value;
}
inline void MotorStatistics::set_disconn_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_disconn_count(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.disconn_count)
}

// float frame_rate = 6;
inline void MotorStatistics::clear_frame_rate() {
  frame_rate_ = 0;
}
inline float MotorStatistics::_internal_frame_rate() const {
  return frame_rate_;
}
inline float MotorStatistics::frame_rate() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.frame_rate)
  return _internal_frame_rate();
}
inline void MotorStatistics::_internal_set_frame_rate(float value) {
  
  frame_rate_ = value;
}
inline void MotorStatistics::set_frame_rate(float value) {
  _internal_set_frame_rate(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.frame_rate)
}

// float failure_rate = 7;
inline void MotorStatistics::clear_failure_rate() {
  failure_rate_ = 0;
}
inline float MotorStatistics::_internal_failure_rate() const {
  return failure_rate_;
}
inline float MotorStatistics::failure_rate() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.failure_rate)
  return _internal_failure_rate();
}
inline void MotorStatistics::_internal_set_failure_rate(float value) {
  
  failure_rate_ = value;
}
inline void MotorStatistics::set_failure_rate(float value) {
  _internal_set_failure_rate(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.failure_rate)
}

// float avg_frame_rate = 8;
inline void MotorStatistics::clear_avg_frame_rate() {
  avg_frame_rate_ = 0;
}
inline float MotorStatistics::_internal_avg_frame_rate() const {
  return avg_frame_rate_;
}
inline float MotorStatistics::avg_frame_rate() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.avg_frame_rate)
  return _internal_avg_frame_rate();
}
inline void MotorStatistics::_internal_set_avg_frame_rate(float value) {
  
  avg_frame_rate_ = value;
}
inline void MotorStatistics::set_avg_frame_rate(float value) {
  _internal_set_avg_frame_rate(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.avg_frame_rate)
}

// float avg_failure_rate = 9;
inline void MotorStatistics::clear_avg_failure_rate() {
  avg_failure_rate_ = 0;
}
inline float MotorStatistics::_internal_avg_failure_rate() const {
  return avg_failure_rate_;
}
inline float MotorStatistics::avg_failure_rate() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.avg_failure_rate)
  return _internal_avg_failure_rate();
}
inline void MotorStatistics::_internal_set_avg_failure_rate(float value) {
  
  avg_failure_rate_ = value;
}
inline void MotorStatistics::set_avg_failure_rate(float value) {
  _internal_set_avg_failure_rate(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.avg_failure_rate)
}

// uint64 duration_ms = 10;
inline void MotorStatistics::clear_duration_ms() {
  duration_ms_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::_internal_duration_ms() const {
  return duration_ms_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MotorStatistics::duration_ms() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.duration_ms)
  return _internal_duration_ms();
}
inline void MotorStatistics::_internal_set_duration_ms(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  duration_ms_ = value;
}
inline void MotorStatistics::set_duration_ms(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_duration_ms(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.duration_ms)
}

// string source_name = 11;
inline void MotorStatistics::clear_source_name() {
  source_name_.ClearToEmpty();
}
inline const std::string& MotorStatistics::source_name() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.source_name)
  return _internal_source_name();
}
inline void MotorStatistics::set_source_name(const std::string& value) {
  _internal_set_source_name(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.source_name)
}
inline std::string* MotorStatistics::mutable_source_name() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.MotorStatistics.source_name)
  return _internal_mutable_source_name();
}
inline const std::string& MotorStatistics::_internal_source_name() const {
  return source_name_.Get();
}
inline void MotorStatistics::_internal_set_source_name(const std::string& value) {
  
  source_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MotorStatistics::set_source_name(std::string&& value) {
  
  source_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.MotorStatistics.source_name)
}
inline void MotorStatistics::set_source_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  source_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.MotorStatistics.source_name)
}
inline void MotorStatistics::set_source_name(const char* value,
    size_t size) {
  
  source_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.MotorStatistics.source_name)
}
inline std::string* MotorStatistics::_internal_mutable_source_name() {
  
  return source_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MotorStatistics::release_source_name() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.MotorStatistics.source_name)
  return source_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MotorStatistics::set_allocated_source_name(std::string* source_name) {
  if (source_name != nullptr) {
    
  } else {
    
  }
  source_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), source_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.MotorStatistics.source_name)
}

// uint32 source_id = 12;
inline void MotorStatistics::clear_source_id() {
  source_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorStatistics::_internal_source_id() const {
  return source_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MotorStatistics::source_id() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.source_id)
  return _internal_source_id();
}
inline void MotorStatistics::_internal_set_source_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  source_id_ = value;
}
inline void MotorStatistics::set_source_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_source_id(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.source_id)
}

// string source_type = 13;
inline void MotorStatistics::clear_source_type() {
  source_type_.ClearToEmpty();
}
inline const std::string& MotorStatistics::source_type() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatistics.source_type)
  return _internal_source_type();
}
inline void MotorStatistics::set_source_type(const std::string& value) {
  _internal_set_source_type(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatistics.source_type)
}
inline std::string* MotorStatistics::mutable_source_type() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.MotorStatistics.source_type)
  return _internal_mutable_source_type();
}
inline const std::string& MotorStatistics::_internal_source_type() const {
  return source_type_.Get();
}
inline void MotorStatistics::_internal_set_source_type(const std::string& value) {
  
  source_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MotorStatistics::set_source_type(std::string&& value) {
  
  source_type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.MotorStatistics.source_type)
}
inline void MotorStatistics::set_source_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  source_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.MotorStatistics.source_type)
}
inline void MotorStatistics::set_source_type(const char* value,
    size_t size) {
  
  source_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.MotorStatistics.source_type)
}
inline std::string* MotorStatistics::_internal_mutable_source_type() {
  
  return source_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MotorStatistics::release_source_type() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.MotorStatistics.source_type)
  return source_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MotorStatistics::set_allocated_source_type(std::string* source_type) {
  if (source_type != nullptr) {
    
  } else {
    
  }
  source_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), source_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.MotorStatistics.source_type)
}

// -------------------------------------------------------------------

// GroupMotorStatistics

// .galbot.core_proto.Header header = 1;
inline bool GroupMotorStatistics::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool GroupMotorStatistics::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& GroupMotorStatistics::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& GroupMotorStatistics::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.header)
  return _internal_header();
}
inline void GroupMotorStatistics::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.GroupMotorStatistics.header)
}
inline ::galbot::core_proto::Header* GroupMotorStatistics::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* GroupMotorStatistics::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.GroupMotorStatistics.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* GroupMotorStatistics::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* GroupMotorStatistics::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.header)
  return _internal_mutable_header();
}
inline void GroupMotorStatistics::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.GroupMotorStatistics.header)
}

// string group_name = 2;
inline void GroupMotorStatistics::clear_group_name() {
  group_name_.ClearToEmpty();
}
inline const std::string& GroupMotorStatistics::group_name() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.group_name)
  return _internal_group_name();
}
inline void GroupMotorStatistics::set_group_name(const std::string& value) {
  _internal_set_group_name(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.group_name)
}
inline std::string* GroupMotorStatistics::mutable_group_name() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.group_name)
  return _internal_mutable_group_name();
}
inline const std::string& GroupMotorStatistics::_internal_group_name() const {
  return group_name_.Get();
}
inline void GroupMotorStatistics::_internal_set_group_name(const std::string& value) {
  
  group_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void GroupMotorStatistics::set_group_name(std::string&& value) {
  
  group_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.GroupMotorStatistics.group_name)
}
inline void GroupMotorStatistics::set_group_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  group_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.GroupMotorStatistics.group_name)
}
inline void GroupMotorStatistics::set_group_name(const char* value,
    size_t size) {
  
  group_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.GroupMotorStatistics.group_name)
}
inline std::string* GroupMotorStatistics::_internal_mutable_group_name() {
  
  return group_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* GroupMotorStatistics::release_group_name() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.GroupMotorStatistics.group_name)
  return group_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GroupMotorStatistics::set_allocated_group_name(std::string* group_name) {
  if (group_name != nullptr) {
    
  } else {
    
  }
  group_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), group_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.GroupMotorStatistics.group_name)
}

// repeated string joint_names = 3;
inline int GroupMotorStatistics::_internal_joint_names_size() const {
  return joint_names_.size();
}
inline int GroupMotorStatistics::joint_names_size() const {
  return _internal_joint_names_size();
}
inline void GroupMotorStatistics::clear_joint_names() {
  joint_names_.Clear();
}
inline std::string* GroupMotorStatistics::add_joint_names() {
  // @@protoc_insertion_point(field_add_mutable:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  return _internal_add_joint_names();
}
inline const std::string& GroupMotorStatistics::_internal_joint_names(int index) const {
  return joint_names_.Get(index);
}
inline const std::string& GroupMotorStatistics::joint_names(int index) const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  return _internal_joint_names(index);
}
inline std::string* GroupMotorStatistics::mutable_joint_names(int index) {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  return joint_names_.Mutable(index);
}
inline void GroupMotorStatistics::set_joint_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  joint_names_.Mutable(index)->assign(value);
}
inline void GroupMotorStatistics::set_joint_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  joint_names_.Mutable(index)->assign(std::move(value));
}
inline void GroupMotorStatistics::set_joint_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  joint_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.GroupMotorStatistics.joint_names)
}
inline void GroupMotorStatistics::set_joint_names(int index, const char* value, size_t size) {
  joint_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.GroupMotorStatistics.joint_names)
}
inline std::string* GroupMotorStatistics::_internal_add_joint_names() {
  return joint_names_.Add();
}
inline void GroupMotorStatistics::add_joint_names(const std::string& value) {
  joint_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:galbot.singorix_proto.GroupMotorStatistics.joint_names)
}
inline void GroupMotorStatistics::add_joint_names(std::string&& value) {
  joint_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:galbot.singorix_proto.GroupMotorStatistics.joint_names)
}
inline void GroupMotorStatistics::add_joint_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  joint_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:galbot.singorix_proto.GroupMotorStatistics.joint_names)
}
inline void GroupMotorStatistics::add_joint_names(const char* value, size_t size) {
  joint_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:galbot.singorix_proto.GroupMotorStatistics.joint_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GroupMotorStatistics::joint_names() const {
  // @@protoc_insertion_point(field_list:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  return joint_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GroupMotorStatistics::mutable_joint_names() {
  // @@protoc_insertion_point(field_mutable_list:galbot.singorix_proto.GroupMotorStatistics.joint_names)
  return &joint_names_;
}

// repeated .galbot.singorix_proto.MotorStatistics statistics = 4;
inline int GroupMotorStatistics::_internal_statistics_size() const {
  return statistics_.size();
}
inline int GroupMotorStatistics::statistics_size() const {
  return _internal_statistics_size();
}
inline void GroupMotorStatistics::clear_statistics() {
  statistics_.Clear();
}
inline ::galbot::singorix_proto::MotorStatistics* GroupMotorStatistics::mutable_statistics(int index) {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.statistics)
  return statistics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::singorix_proto::MotorStatistics >*
GroupMotorStatistics::mutable_statistics() {
  // @@protoc_insertion_point(field_mutable_list:galbot.singorix_proto.GroupMotorStatistics.statistics)
  return &statistics_;
}
inline const ::galbot::singorix_proto::MotorStatistics& GroupMotorStatistics::_internal_statistics(int index) const {
  return statistics_.Get(index);
}
inline const ::galbot::singorix_proto::MotorStatistics& GroupMotorStatistics::statistics(int index) const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.statistics)
  return _internal_statistics(index);
}
inline ::galbot::singorix_proto::MotorStatistics* GroupMotorStatistics::_internal_add_statistics() {
  return statistics_.Add();
}
inline ::galbot::singorix_proto::MotorStatistics* GroupMotorStatistics::add_statistics() {
  // @@protoc_insertion_point(field_add:galbot.singorix_proto.GroupMotorStatistics.statistics)
  return _internal_add_statistics();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::galbot::singorix_proto::MotorStatistics >&
GroupMotorStatistics::statistics() const {
  // @@protoc_insertion_point(field_list:galbot.singorix_proto.GroupMotorStatistics.statistics)
  return statistics_;
}

// repeated string source_names = 5;
inline int GroupMotorStatistics::_internal_source_names_size() const {
  return source_names_.size();
}
inline int GroupMotorStatistics::source_names_size() const {
  return _internal_source_names_size();
}
inline void GroupMotorStatistics::clear_source_names() {
  source_names_.Clear();
}
inline std::string* GroupMotorStatistics::add_source_names() {
  // @@protoc_insertion_point(field_add_mutable:galbot.singorix_proto.GroupMotorStatistics.source_names)
  return _internal_add_source_names();
}
inline const std::string& GroupMotorStatistics::_internal_source_names(int index) const {
  return source_names_.Get(index);
}
inline const std::string& GroupMotorStatistics::source_names(int index) const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.source_names)
  return _internal_source_names(index);
}
inline std::string* GroupMotorStatistics::mutable_source_names(int index) {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.source_names)
  return source_names_.Mutable(index);
}
inline void GroupMotorStatistics::set_source_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.source_names)
  source_names_.Mutable(index)->assign(value);
}
inline void GroupMotorStatistics::set_source_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.source_names)
  source_names_.Mutable(index)->assign(std::move(value));
}
inline void GroupMotorStatistics::set_source_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  source_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.GroupMotorStatistics.source_names)
}
inline void GroupMotorStatistics::set_source_names(int index, const char* value, size_t size) {
  source_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.GroupMotorStatistics.source_names)
}
inline std::string* GroupMotorStatistics::_internal_add_source_names() {
  return source_names_.Add();
}
inline void GroupMotorStatistics::add_source_names(const std::string& value) {
  source_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:galbot.singorix_proto.GroupMotorStatistics.source_names)
}
inline void GroupMotorStatistics::add_source_names(std::string&& value) {
  source_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:galbot.singorix_proto.GroupMotorStatistics.source_names)
}
inline void GroupMotorStatistics::add_source_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  source_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:galbot.singorix_proto.GroupMotorStatistics.source_names)
}
inline void GroupMotorStatistics::add_source_names(const char* value, size_t size) {
  source_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:galbot.singorix_proto.GroupMotorStatistics.source_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GroupMotorStatistics::source_names() const {
  // @@protoc_insertion_point(field_list:galbot.singorix_proto.GroupMotorStatistics.source_names)
  return source_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GroupMotorStatistics::mutable_source_names() {
  // @@protoc_insertion_point(field_mutable_list:galbot.singorix_proto.GroupMotorStatistics.source_names)
  return &source_names_;
}

// repeated uint32 source_ids = 6;
inline int GroupMotorStatistics::_internal_source_ids_size() const {
  return source_ids_.size();
}
inline int GroupMotorStatistics::source_ids_size() const {
  return _internal_source_ids_size();
}
inline void GroupMotorStatistics::clear_source_ids() {
  source_ids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GroupMotorStatistics::_internal_source_ids(int index) const {
  return source_ids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GroupMotorStatistics::source_ids(int index) const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.source_ids)
  return _internal_source_ids(index);
}
inline void GroupMotorStatistics::set_source_ids(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  source_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.source_ids)
}
inline void GroupMotorStatistics::_internal_add_source_ids(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  source_ids_.Add(value);
}
inline void GroupMotorStatistics::add_source_ids(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_source_ids(value);
  // @@protoc_insertion_point(field_add:galbot.singorix_proto.GroupMotorStatistics.source_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
GroupMotorStatistics::_internal_source_ids() const {
  return source_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
GroupMotorStatistics::source_ids() const {
  // @@protoc_insertion_point(field_list:galbot.singorix_proto.GroupMotorStatistics.source_ids)
  return _internal_source_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
GroupMotorStatistics::_internal_mutable_source_ids() {
  return &source_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
GroupMotorStatistics::mutable_source_ids() {
  // @@protoc_insertion_point(field_mutable_list:galbot.singorix_proto.GroupMotorStatistics.source_ids)
  return _internal_mutable_source_ids();
}

// string interface_name = 7;
inline void GroupMotorStatistics::clear_interface_name() {
  interface_name_.ClearToEmpty();
}
inline const std::string& GroupMotorStatistics::interface_name() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.interface_name)
  return _internal_interface_name();
}
inline void GroupMotorStatistics::set_interface_name(const std::string& value) {
  _internal_set_interface_name(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.interface_name)
}
inline std::string* GroupMotorStatistics::mutable_interface_name() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.interface_name)
  return _internal_mutable_interface_name();
}
inline const std::string& GroupMotorStatistics::_internal_interface_name() const {
  return interface_name_.Get();
}
inline void GroupMotorStatistics::_internal_set_interface_name(const std::string& value) {
  
  interface_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void GroupMotorStatistics::set_interface_name(std::string&& value) {
  
  interface_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.GroupMotorStatistics.interface_name)
}
inline void GroupMotorStatistics::set_interface_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  interface_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.GroupMotorStatistics.interface_name)
}
inline void GroupMotorStatistics::set_interface_name(const char* value,
    size_t size) {
  
  interface_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.GroupMotorStatistics.interface_name)
}
inline std::string* GroupMotorStatistics::_internal_mutable_interface_name() {
  
  return interface_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* GroupMotorStatistics::release_interface_name() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.GroupMotorStatistics.interface_name)
  return interface_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GroupMotorStatistics::set_allocated_interface_name(std::string* interface_name) {
  if (interface_name != nullptr) {
    
  } else {
    
  }
  interface_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), interface_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.GroupMotorStatistics.interface_name)
}

// string device_name = 8;
inline void GroupMotorStatistics::clear_device_name() {
  device_name_.ClearToEmpty();
}
inline const std::string& GroupMotorStatistics::device_name() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.GroupMotorStatistics.device_name)
  return _internal_device_name();
}
inline void GroupMotorStatistics::set_device_name(const std::string& value) {
  _internal_set_device_name(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.GroupMotorStatistics.device_name)
}
inline std::string* GroupMotorStatistics::mutable_device_name() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.GroupMotorStatistics.device_name)
  return _internal_mutable_device_name();
}
inline const std::string& GroupMotorStatistics::_internal_device_name() const {
  return device_name_.Get();
}
inline void GroupMotorStatistics::_internal_set_device_name(const std::string& value) {
  
  device_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void GroupMotorStatistics::set_device_name(std::string&& value) {
  
  device_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.GroupMotorStatistics.device_name)
}
inline void GroupMotorStatistics::set_device_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  device_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.GroupMotorStatistics.device_name)
}
inline void GroupMotorStatistics::set_device_name(const char* value,
    size_t size) {
  
  device_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.GroupMotorStatistics.device_name)
}
inline std::string* GroupMotorStatistics::_internal_mutable_device_name() {
  
  return device_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* GroupMotorStatistics::release_device_name() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.GroupMotorStatistics.device_name)
  return device_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GroupMotorStatistics::set_allocated_device_name(std::string* device_name) {
  if (device_name != nullptr) {
    
  } else {
    
  }
  device_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), device_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.GroupMotorStatistics.device_name)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MotorStatisticsReport

// .galbot.core_proto.Header header = 1;
inline bool MotorStatisticsReport::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool MotorStatisticsReport::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& MotorStatisticsReport::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& MotorStatisticsReport::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatisticsReport.header)
  return _internal_header();
}
inline void MotorStatisticsReport::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.MotorStatisticsReport.header)
}
inline ::galbot::core_proto::Header* MotorStatisticsReport::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* MotorStatisticsReport::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.MotorStatisticsReport.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* MotorStatisticsReport::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* MotorStatisticsReport::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.MotorStatisticsReport.header)
  return _internal_mutable_header();
}
inline void MotorStatisticsReport::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.MotorStatisticsReport.header)
}

// string robot_model = 2;
inline void MotorStatisticsReport::clear_robot_model() {
  robot_model_.ClearToEmpty();
}
inline const std::string& MotorStatisticsReport::robot_model() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.MotorStatisticsReport.robot_model)
  return _internal_robot_model();
}
inline void MotorStatisticsReport::set_robot_model(const std::string& value) {
  _internal_set_robot_model(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.MotorStatisticsReport.robot_model)
}
inline std::string* MotorStatisticsReport::mutable_robot_model() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.MotorStatisticsReport.robot_model)
  return _internal_mutable_robot_model();
}
inline const std::string& MotorStatisticsReport::_internal_robot_model() const {
  return robot_model_.Get();
}
inline void MotorStatisticsReport::_internal_set_robot_model(const std::string& value) {
  
  robot_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MotorStatisticsReport::set_robot_model(std::string&& value) {
  
  robot_model_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.MotorStatisticsReport.robot_model)
}
inline void MotorStatisticsReport::set_robot_model(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  robot_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.MotorStatisticsReport.robot_model)
}
inline void MotorStatisticsReport::set_robot_model(const char* value,
    size_t size) {
  
  robot_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.MotorStatisticsReport.robot_model)
}
inline std::string* MotorStatisticsReport::_internal_mutable_robot_model() {
  
  return robot_model_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MotorStatisticsReport::release_robot_model() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.MotorStatisticsReport.robot_model)
  return robot_model_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MotorStatisticsReport::set_allocated_robot_model(std::string* robot_model) {
  if (robot_model != nullptr) {
    
  } else {
    
  }
  robot_model_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), robot_model,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.MotorStatisticsReport.robot_model)
}

// map<string, .galbot.singorix_proto.GroupMotorStatistics> group_statistics_map = 3;
inline int MotorStatisticsReport::_internal_group_statistics_map_size() const {
  return group_statistics_map_.size();
}
inline int MotorStatisticsReport::group_statistics_map_size() const {
  return _internal_group_statistics_map_size();
}
inline void MotorStatisticsReport::clear_group_statistics_map() {
  group_statistics_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
MotorStatisticsReport::_internal_group_statistics_map() const {
  return group_statistics_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
MotorStatisticsReport::group_statistics_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.MotorStatisticsReport.group_statistics_map)
  return _internal_group_statistics_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
MotorStatisticsReport::_internal_mutable_group_statistics_map() {
  return group_statistics_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
MotorStatisticsReport::mutable_group_statistics_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.MotorStatisticsReport.group_statistics_map)
  return _internal_mutable_group_statistics_map();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Nx1MotorStatistics

// .galbot.core_proto.Header header = 1;
inline bool Nx1MotorStatistics::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Nx1MotorStatistics::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& Nx1MotorStatistics::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& Nx1MotorStatistics::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.Nx1MotorStatistics.header)
  return _internal_header();
}
inline void Nx1MotorStatistics::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.Nx1MotorStatistics.header)
}
inline ::galbot::core_proto::Header* Nx1MotorStatistics::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* Nx1MotorStatistics::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.Nx1MotorStatistics.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* Nx1MotorStatistics::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* Nx1MotorStatistics::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.Nx1MotorStatistics.header)
  return _internal_mutable_header();
}
inline void Nx1MotorStatistics::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.Nx1MotorStatistics.header)
}

// map<string, .galbot.singorix_proto.GroupMotorStatistics> group_statistics_map = 2;
inline int Nx1MotorStatistics::_internal_group_statistics_map_size() const {
  return group_statistics_map_.size();
}
inline int Nx1MotorStatistics::group_statistics_map_size() const {
  return _internal_group_statistics_map_size();
}
inline void Nx1MotorStatistics::clear_group_statistics_map() {
  group_statistics_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
Nx1MotorStatistics::_internal_group_statistics_map() const {
  return group_statistics_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >&
Nx1MotorStatistics::group_statistics_map() const {
  // @@protoc_insertion_point(field_map:galbot.singorix_proto.Nx1MotorStatistics.group_statistics_map)
  return _internal_group_statistics_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
Nx1MotorStatistics::_internal_mutable_group_statistics_map() {
  return group_statistics_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::galbot::singorix_proto::GroupMotorStatistics >*
Nx1MotorStatistics::mutable_group_statistics_map() {
  // @@protoc_insertion_point(field_mutable_map:galbot.singorix_proto.Nx1MotorStatistics.group_statistics_map)
  return _internal_mutable_group_statistics_map();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace singorix_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fmotor_5fstatistics_2eproto
