// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/mission_proto/reception.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fmission_5fproto_2freception_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fmission_5fproto_2freception_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fmission_5fproto_2freception_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fmission_5fproto_2freception_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fmission_5fproto_2freception_2eproto;
class Reception;
class ReceptionDefaultTypeInternal;
extern ReceptionDefaultTypeInternal _Reception_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Reception* Arena::CreateMaybeMessage<::Reception>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum RobotState : int {
  ROBOT_UNKNOWN = 0,
  ROBOT_ERROR = 1,
  ROBOT_OFFLINE = 2,
  ROBOT_IDLING_PATROL = 3,
  ROBOT_GREETING_FACE = 4,
  ROBOT_WAKING_UP = 5,
  ROBOT_IDLE = 6,
  ROBOT_LISTENING = 7,
  ROBOT_THINKING = 8,
  ROBOT_SPEAKING = 9,
  ROBOT_EXECUTING_CRITICAL_ACTION = 10,
  ROBOT_PICKING_ORDER = 11,
  RobotState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  RobotState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool RobotState_IsValid(int value);
constexpr RobotState RobotState_MIN = ROBOT_UNKNOWN;
constexpr RobotState RobotState_MAX = ROBOT_PICKING_ORDER;
constexpr int RobotState_ARRAYSIZE = RobotState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RobotState_descriptor();
template<typename T>
inline const std::string& RobotState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RobotState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RobotState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RobotState_descriptor(), enum_t_value);
}
inline bool RobotState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RobotState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RobotState>(
    RobotState_descriptor(), name, value);
}
// ===================================================================

class Reception PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Reception) */ {
 public:
  inline Reception() : Reception(nullptr) {}
  virtual ~Reception();

  Reception(const Reception& from);
  Reception(Reception&& from) noexcept
    : Reception() {
    *this = ::std::move(from);
  }

  inline Reception& operator=(const Reception& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reception& operator=(Reception&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Reception& default_instance();

  static inline const Reception* internal_default_instance() {
    return reinterpret_cast<const Reception*>(
               &_Reception_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Reception& a, Reception& b) {
    a.Swap(&b);
  }
  inline void Swap(Reception* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reception* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Reception* New() const final {
    return CreateMaybeMessage<Reception>(nullptr);
  }

  Reception* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Reception>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Reception& from);
  void MergeFrom(const Reception& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reception* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Reception";
  }
  protected:
  explicit Reception(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fmission_5fproto_2freception_2eproto);
    return ::descriptor_table_galbot_2fmission_5fproto_2freception_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kStateFieldNumber = 2,
  };
  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // .RobotState state = 2;
  void clear_state();
  ::RobotState state() const;
  void set_state(::RobotState value);
  private:
  ::RobotState _internal_state() const;
  void _internal_set_state(::RobotState value);
  public:

  // @@protoc_insertion_point(class_scope:Reception)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::galbot::core_proto::Header* header_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fmission_5fproto_2freception_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Reception

// .galbot.core_proto.Header header = 1;
inline bool Reception::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Reception::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& Reception::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& Reception::header() const {
  // @@protoc_insertion_point(field_get:Reception.header)
  return _internal_header();
}
inline void Reception::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Reception.header)
}
inline ::galbot::core_proto::Header* Reception::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* Reception::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:Reception.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* Reception::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* Reception::mutable_header() {
  // @@protoc_insertion_point(field_mutable:Reception.header)
  return _internal_mutable_header();
}
inline void Reception::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:Reception.header)
}

// .RobotState state = 2;
inline void Reception::clear_state() {
  state_ = 0;
}
inline ::RobotState Reception::_internal_state() const {
  return static_cast< ::RobotState >(state_);
}
inline ::RobotState Reception::state() const {
  // @@protoc_insertion_point(field_get:Reception.state)
  return _internal_state();
}
inline void Reception::_internal_set_state(::RobotState value) {
  
  state_ = value;
}
inline void Reception::set_state(::RobotState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Reception.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RobotState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RobotState>() {
  return ::RobotState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fmission_5fproto_2freception_2eproto
