// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/mission_proto/task_status.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto;
namespace galbot {
namespace mission_proto {
class TaskStatus;
class TaskStatusDefaultTypeInternal;
extern TaskStatusDefaultTypeInternal _TaskStatus_default_instance_;
}  // namespace mission_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::mission_proto::TaskStatus* Arena::CreateMaybeMessage<::galbot::mission_proto::TaskStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace mission_proto {

enum MainStatus : int {
  UNKNOWN_MAIN_STATUS = 0,
  WORKING = 1,
  ERROR = 2,
  MainStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MainStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool MainStatus_IsValid(int value);
constexpr MainStatus MainStatus_MIN = UNKNOWN_MAIN_STATUS;
constexpr MainStatus MainStatus_MAX = ERROR;
constexpr int MainStatus_ARRAYSIZE = MainStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MainStatus_descriptor();
template<typename T>
inline const std::string& MainStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MainStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MainStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MainStatus_descriptor(), enum_t_value);
}
inline bool MainStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MainStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MainStatus>(
    MainStatus_descriptor(), name, value);
}
enum WorkingSubStatus : int {
  UNKNOWN_WORKING_SUB_STATUS = 0,
  GOING_HOME = 1,
  IDLE = 2,
  GOING_TO_TARGET = 3,
  PICKING_FROM_SHELF = 4,
  GOING_TO_PACKING = 5,
  PLACING_INTO_PACK = 6,
  REPORTING_ORDER_SUCCESS = 7,
  REPORTING_ORDER_FAILURE = 8,
  ORDER_RECEIVED = 9,
  WorkingSubStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  WorkingSubStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool WorkingSubStatus_IsValid(int value);
constexpr WorkingSubStatus WorkingSubStatus_MIN = UNKNOWN_WORKING_SUB_STATUS;
constexpr WorkingSubStatus WorkingSubStatus_MAX = ORDER_RECEIVED;
constexpr int WorkingSubStatus_ARRAYSIZE = WorkingSubStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WorkingSubStatus_descriptor();
template<typename T>
inline const std::string& WorkingSubStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WorkingSubStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WorkingSubStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WorkingSubStatus_descriptor(), enum_t_value);
}
inline bool WorkingSubStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WorkingSubStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WorkingSubStatus>(
    WorkingSubStatus_descriptor(), name, value);
}
enum PickingSubStatus : int {
  UNKNOWN_PICKING_SUB_STATUS = 0,
  OBSERVING = 1,
  GRABBING = 2,
  RECOVERING = 3,
  PickingSubStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PickingSubStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PickingSubStatus_IsValid(int value);
constexpr PickingSubStatus PickingSubStatus_MIN = UNKNOWN_PICKING_SUB_STATUS;
constexpr PickingSubStatus PickingSubStatus_MAX = RECOVERING;
constexpr int PickingSubStatus_ARRAYSIZE = PickingSubStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PickingSubStatus_descriptor();
template<typename T>
inline const std::string& PickingSubStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PickingSubStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PickingSubStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PickingSubStatus_descriptor(), enum_t_value);
}
inline bool PickingSubStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PickingSubStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PickingSubStatus>(
    PickingSubStatus_descriptor(), name, value);
}
enum PlacingSubStatus : int {
  UNKNOWN_PLACING_SUB_STATUS = 0,
  PRE_PLACING = 1,
  PLACING = 2,
  RETRACTING = 3,
  FINISHED = 4,
  PlacingSubStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PlacingSubStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PlacingSubStatus_IsValid(int value);
constexpr PlacingSubStatus PlacingSubStatus_MIN = UNKNOWN_PLACING_SUB_STATUS;
constexpr PlacingSubStatus PlacingSubStatus_MAX = FINISHED;
constexpr int PlacingSubStatus_ARRAYSIZE = PlacingSubStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlacingSubStatus_descriptor();
template<typename T>
inline const std::string& PlacingSubStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlacingSubStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlacingSubStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlacingSubStatus_descriptor(), enum_t_value);
}
inline bool PlacingSubStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlacingSubStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlacingSubStatus>(
    PlacingSubStatus_descriptor(), name, value);
}
// ===================================================================

class TaskStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.mission_proto.TaskStatus) */ {
 public:
  inline TaskStatus() : TaskStatus(nullptr) {}
  virtual ~TaskStatus();

  TaskStatus(const TaskStatus& from);
  TaskStatus(TaskStatus&& from) noexcept
    : TaskStatus() {
    *this = ::std::move(from);
  }

  inline TaskStatus& operator=(const TaskStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskStatus& operator=(TaskStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TaskStatus& default_instance();

  static inline const TaskStatus* internal_default_instance() {
    return reinterpret_cast<const TaskStatus*>(
               &_TaskStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TaskStatus& a, TaskStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TaskStatus* New() const final {
    return CreateMaybeMessage<TaskStatus>(nullptr);
  }

  TaskStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TaskStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TaskStatus& from);
  void MergeFrom(const TaskStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.mission_proto.TaskStatus";
  }
  protected:
  explicit TaskStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto);
    return ::descriptor_table_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kTaskIdFieldNumber = 2,
    kSubTaskIdFieldNumber = 3,
    kMainStatusFieldNumber = 4,
    kWorkingSubStatusFieldNumber = 5,
    kPickingSubStatusFieldNumber = 6,
    kPlacingSubStatusFieldNumber = 7,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  void set_uuid(const std::string& value);
  void set_uuid(std::string&& value);
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  std::string* mutable_uuid();
  std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // int32 task_id = 2;
  void clear_task_id();
  ::PROTOBUF_NAMESPACE_ID::int32 task_id() const;
  void set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_task_id() const;
  void _internal_set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 sub_task_id = 3;
  void clear_sub_task_id();
  ::PROTOBUF_NAMESPACE_ID::int32 sub_task_id() const;
  void set_sub_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sub_task_id() const;
  void _internal_set_sub_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .galbot.mission_proto.MainStatus main_status = 4;
  void clear_main_status();
  ::galbot::mission_proto::MainStatus main_status() const;
  void set_main_status(::galbot::mission_proto::MainStatus value);
  private:
  ::galbot::mission_proto::MainStatus _internal_main_status() const;
  void _internal_set_main_status(::galbot::mission_proto::MainStatus value);
  public:

  // .galbot.mission_proto.WorkingSubStatus working_sub_status = 5;
  void clear_working_sub_status();
  ::galbot::mission_proto::WorkingSubStatus working_sub_status() const;
  void set_working_sub_status(::galbot::mission_proto::WorkingSubStatus value);
  private:
  ::galbot::mission_proto::WorkingSubStatus _internal_working_sub_status() const;
  void _internal_set_working_sub_status(::galbot::mission_proto::WorkingSubStatus value);
  public:

  // .galbot.mission_proto.PickingSubStatus picking_sub_status = 6;
  void clear_picking_sub_status();
  ::galbot::mission_proto::PickingSubStatus picking_sub_status() const;
  void set_picking_sub_status(::galbot::mission_proto::PickingSubStatus value);
  private:
  ::galbot::mission_proto::PickingSubStatus _internal_picking_sub_status() const;
  void _internal_set_picking_sub_status(::galbot::mission_proto::PickingSubStatus value);
  public:

  // .galbot.mission_proto.PlacingSubStatus placing_sub_status = 7;
  void clear_placing_sub_status();
  ::galbot::mission_proto::PlacingSubStatus placing_sub_status() const;
  void set_placing_sub_status(::galbot::mission_proto::PlacingSubStatus value);
  private:
  ::galbot::mission_proto::PlacingSubStatus _internal_placing_sub_status() const;
  void _internal_set_placing_sub_status(::galbot::mission_proto::PlacingSubStatus value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.mission_proto.TaskStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  ::PROTOBUF_NAMESPACE_ID::int32 task_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 sub_task_id_;
  int main_status_;
  int working_sub_status_;
  int picking_sub_status_;
  int placing_sub_status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TaskStatus

// string uuid = 1;
inline void TaskStatus::clear_uuid() {
  uuid_.ClearToEmpty();
}
inline const std::string& TaskStatus::uuid() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.uuid)
  return _internal_uuid();
}
inline void TaskStatus::set_uuid(const std::string& value) {
  _internal_set_uuid(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.uuid)
}
inline std::string* TaskStatus::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable:galbot.mission_proto.TaskStatus.uuid)
  return _internal_mutable_uuid();
}
inline const std::string& TaskStatus::_internal_uuid() const {
  return uuid_.Get();
}
inline void TaskStatus::_internal_set_uuid(const std::string& value) {
  
  uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TaskStatus::set_uuid(std::string&& value) {
  
  uuid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.mission_proto.TaskStatus.uuid)
}
inline void TaskStatus::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.mission_proto.TaskStatus.uuid)
}
inline void TaskStatus::set_uuid(const char* value,
    size_t size) {
  
  uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.mission_proto.TaskStatus.uuid)
}
inline std::string* TaskStatus::_internal_mutable_uuid() {
  
  return uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TaskStatus::release_uuid() {
  // @@protoc_insertion_point(field_release:galbot.mission_proto.TaskStatus.uuid)
  return uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TaskStatus::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.mission_proto.TaskStatus.uuid)
}

// int32 task_id = 2;
inline void TaskStatus::clear_task_id() {
  task_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TaskStatus::_internal_task_id() const {
  return task_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TaskStatus::task_id() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.task_id)
  return _internal_task_id();
}
inline void TaskStatus::_internal_set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  task_id_ = value;
}
inline void TaskStatus::set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.task_id)
}

// int32 sub_task_id = 3;
inline void TaskStatus::clear_sub_task_id() {
  sub_task_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TaskStatus::_internal_sub_task_id() const {
  return sub_task_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TaskStatus::sub_task_id() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.sub_task_id)
  return _internal_sub_task_id();
}
inline void TaskStatus::_internal_set_sub_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sub_task_id_ = value;
}
inline void TaskStatus::set_sub_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sub_task_id(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.sub_task_id)
}

// .galbot.mission_proto.MainStatus main_status = 4;
inline void TaskStatus::clear_main_status() {
  main_status_ = 0;
}
inline ::galbot::mission_proto::MainStatus TaskStatus::_internal_main_status() const {
  return static_cast< ::galbot::mission_proto::MainStatus >(main_status_);
}
inline ::galbot::mission_proto::MainStatus TaskStatus::main_status() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.main_status)
  return _internal_main_status();
}
inline void TaskStatus::_internal_set_main_status(::galbot::mission_proto::MainStatus value) {
  
  main_status_ = value;
}
inline void TaskStatus::set_main_status(::galbot::mission_proto::MainStatus value) {
  _internal_set_main_status(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.main_status)
}

// .galbot.mission_proto.WorkingSubStatus working_sub_status = 5;
inline void TaskStatus::clear_working_sub_status() {
  working_sub_status_ = 0;
}
inline ::galbot::mission_proto::WorkingSubStatus TaskStatus::_internal_working_sub_status() const {
  return static_cast< ::galbot::mission_proto::WorkingSubStatus >(working_sub_status_);
}
inline ::galbot::mission_proto::WorkingSubStatus TaskStatus::working_sub_status() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.working_sub_status)
  return _internal_working_sub_status();
}
inline void TaskStatus::_internal_set_working_sub_status(::galbot::mission_proto::WorkingSubStatus value) {
  
  working_sub_status_ = value;
}
inline void TaskStatus::set_working_sub_status(::galbot::mission_proto::WorkingSubStatus value) {
  _internal_set_working_sub_status(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.working_sub_status)
}

// .galbot.mission_proto.PickingSubStatus picking_sub_status = 6;
inline void TaskStatus::clear_picking_sub_status() {
  picking_sub_status_ = 0;
}
inline ::galbot::mission_proto::PickingSubStatus TaskStatus::_internal_picking_sub_status() const {
  return static_cast< ::galbot::mission_proto::PickingSubStatus >(picking_sub_status_);
}
inline ::galbot::mission_proto::PickingSubStatus TaskStatus::picking_sub_status() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.picking_sub_status)
  return _internal_picking_sub_status();
}
inline void TaskStatus::_internal_set_picking_sub_status(::galbot::mission_proto::PickingSubStatus value) {
  
  picking_sub_status_ = value;
}
inline void TaskStatus::set_picking_sub_status(::galbot::mission_proto::PickingSubStatus value) {
  _internal_set_picking_sub_status(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.picking_sub_status)
}

// .galbot.mission_proto.PlacingSubStatus placing_sub_status = 7;
inline void TaskStatus::clear_placing_sub_status() {
  placing_sub_status_ = 0;
}
inline ::galbot::mission_proto::PlacingSubStatus TaskStatus::_internal_placing_sub_status() const {
  return static_cast< ::galbot::mission_proto::PlacingSubStatus >(placing_sub_status_);
}
inline ::galbot::mission_proto::PlacingSubStatus TaskStatus::placing_sub_status() const {
  // @@protoc_insertion_point(field_get:galbot.mission_proto.TaskStatus.placing_sub_status)
  return _internal_placing_sub_status();
}
inline void TaskStatus::_internal_set_placing_sub_status(::galbot::mission_proto::PlacingSubStatus value) {
  
  placing_sub_status_ = value;
}
inline void TaskStatus::set_placing_sub_status(::galbot::mission_proto::PlacingSubStatus value) {
  _internal_set_placing_sub_status(value);
  // @@protoc_insertion_point(field_set:galbot.mission_proto.TaskStatus.placing_sub_status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mission_proto
}  // namespace galbot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::galbot::mission_proto::MainStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::mission_proto::MainStatus>() {
  return ::galbot::mission_proto::MainStatus_descriptor();
}
template <> struct is_proto_enum< ::galbot::mission_proto::WorkingSubStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::mission_proto::WorkingSubStatus>() {
  return ::galbot::mission_proto::WorkingSubStatus_descriptor();
}
template <> struct is_proto_enum< ::galbot::mission_proto::PickingSubStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::mission_proto::PickingSubStatus>() {
  return ::galbot::mission_proto::PickingSubStatus_descriptor();
}
template <> struct is_proto_enum< ::galbot::mission_proto::PlacingSubStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::galbot::mission_proto::PlacingSubStatus>() {
  return ::galbot::mission_proto::PlacingSubStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fmission_5fproto_2ftask_5fstatus_2eproto
