// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: galbot/singorix_proto/singorix_passthrough.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "galbot/core_proto/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto;
namespace galbot {
namespace singorix_proto {
class EndToolRawCommand;
class EndToolRawCommandDefaultTypeInternal;
extern EndToolRawCommandDefaultTypeInternal _EndToolRawCommand_default_instance_;
class EndToolRawData;
class EndToolRawDataDefaultTypeInternal;
extern EndToolRawDataDefaultTypeInternal _EndToolRawData_default_instance_;
}  // namespace singorix_proto
}  // namespace galbot
PROTOBUF_NAMESPACE_OPEN
template<> ::galbot::singorix_proto::EndToolRawCommand* Arena::CreateMaybeMessage<::galbot::singorix_proto::EndToolRawCommand>(Arena*);
template<> ::galbot::singorix_proto::EndToolRawData* Arena::CreateMaybeMessage<::galbot::singorix_proto::EndToolRawData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace galbot {
namespace singorix_proto {

// ===================================================================

class EndToolRawData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.EndToolRawData) */ {
 public:
  inline EndToolRawData() : EndToolRawData(nullptr) {}
  virtual ~EndToolRawData();

  EndToolRawData(const EndToolRawData& from);
  EndToolRawData(EndToolRawData&& from) noexcept
    : EndToolRawData() {
    *this = ::std::move(from);
  }

  inline EndToolRawData& operator=(const EndToolRawData& from) {
    CopyFrom(from);
    return *this;
  }
  inline EndToolRawData& operator=(EndToolRawData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EndToolRawData& default_instance();

  static inline const EndToolRawData* internal_default_instance() {
    return reinterpret_cast<const EndToolRawData*>(
               &_EndToolRawData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EndToolRawData& a, EndToolRawData& b) {
    a.Swap(&b);
  }
  inline void Swap(EndToolRawData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EndToolRawData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EndToolRawData* New() const final {
    return CreateMaybeMessage<EndToolRawData>(nullptr);
  }

  EndToolRawData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EndToolRawData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EndToolRawData& from);
  void MergeFrom(const EndToolRawData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EndToolRawData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.EndToolRawData";
  }
  protected:
  explicit EndToolRawData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEndpointIdFieldNumber = 2,
    kChannelIdFieldNumber = 3,
    kPayloadFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kSequenceFieldNumber = 5,
  };
  // string endpoint_id = 2;
  void clear_endpoint_id();
  const std::string& endpoint_id() const;
  void set_endpoint_id(const std::string& value);
  void set_endpoint_id(std::string&& value);
  void set_endpoint_id(const char* value);
  void set_endpoint_id(const char* value, size_t size);
  std::string* mutable_endpoint_id();
  std::string* release_endpoint_id();
  void set_allocated_endpoint_id(std::string* endpoint_id);
  private:
  const std::string& _internal_endpoint_id() const;
  void _internal_set_endpoint_id(const std::string& value);
  std::string* _internal_mutable_endpoint_id();
  public:

  // string channel_id = 3;
  void clear_channel_id();
  const std::string& channel_id() const;
  void set_channel_id(const std::string& value);
  void set_channel_id(std::string&& value);
  void set_channel_id(const char* value);
  void set_channel_id(const char* value, size_t size);
  std::string* mutable_channel_id();
  std::string* release_channel_id();
  void set_allocated_channel_id(std::string* channel_id);
  private:
  const std::string& _internal_channel_id() const;
  void _internal_set_channel_id(const std::string& value);
  std::string* _internal_mutable_channel_id();
  public:

  // bytes payload = 4;
  void clear_payload();
  const std::string& payload() const;
  void set_payload(const std::string& value);
  void set_payload(std::string&& value);
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  std::string* mutable_payload();
  std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // uint64 sequence = 5;
  void clear_sequence();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequence() const;
  void set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequence() const;
  void _internal_set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.EndToolRawData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr endpoint_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr channel_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
  ::galbot::core_proto::Header* header_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequence_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto;
};
// -------------------------------------------------------------------

class EndToolRawCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:galbot.singorix_proto.EndToolRawCommand) */ {
 public:
  inline EndToolRawCommand() : EndToolRawCommand(nullptr) {}
  virtual ~EndToolRawCommand();

  EndToolRawCommand(const EndToolRawCommand& from);
  EndToolRawCommand(EndToolRawCommand&& from) noexcept
    : EndToolRawCommand() {
    *this = ::std::move(from);
  }

  inline EndToolRawCommand& operator=(const EndToolRawCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline EndToolRawCommand& operator=(EndToolRawCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EndToolRawCommand& default_instance();

  static inline const EndToolRawCommand* internal_default_instance() {
    return reinterpret_cast<const EndToolRawCommand*>(
               &_EndToolRawCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EndToolRawCommand& a, EndToolRawCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(EndToolRawCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EndToolRawCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EndToolRawCommand* New() const final {
    return CreateMaybeMessage<EndToolRawCommand>(nullptr);
  }

  EndToolRawCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EndToolRawCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EndToolRawCommand& from);
  void MergeFrom(const EndToolRawCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EndToolRawCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "galbot.singorix_proto.EndToolRawCommand";
  }
  protected:
  explicit EndToolRawCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto);
    return ::descriptor_table_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEndpointIdFieldNumber = 2,
    kChannelIdFieldNumber = 3,
    kPayloadFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kSequenceFieldNumber = 5,
  };
  // string endpoint_id = 2;
  void clear_endpoint_id();
  const std::string& endpoint_id() const;
  void set_endpoint_id(const std::string& value);
  void set_endpoint_id(std::string&& value);
  void set_endpoint_id(const char* value);
  void set_endpoint_id(const char* value, size_t size);
  std::string* mutable_endpoint_id();
  std::string* release_endpoint_id();
  void set_allocated_endpoint_id(std::string* endpoint_id);
  private:
  const std::string& _internal_endpoint_id() const;
  void _internal_set_endpoint_id(const std::string& value);
  std::string* _internal_mutable_endpoint_id();
  public:

  // string channel_id = 3;
  void clear_channel_id();
  const std::string& channel_id() const;
  void set_channel_id(const std::string& value);
  void set_channel_id(std::string&& value);
  void set_channel_id(const char* value);
  void set_channel_id(const char* value, size_t size);
  std::string* mutable_channel_id();
  std::string* release_channel_id();
  void set_allocated_channel_id(std::string* channel_id);
  private:
  const std::string& _internal_channel_id() const;
  void _internal_set_channel_id(const std::string& value);
  std::string* _internal_mutable_channel_id();
  public:

  // bytes payload = 4;
  void clear_payload();
  const std::string& payload() const;
  void set_payload(const std::string& value);
  void set_payload(std::string&& value);
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  std::string* mutable_payload();
  std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // .galbot.core_proto.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::galbot::core_proto::Header& header() const;
  ::galbot::core_proto::Header* release_header();
  ::galbot::core_proto::Header* mutable_header();
  void set_allocated_header(::galbot::core_proto::Header* header);
  private:
  const ::galbot::core_proto::Header& _internal_header() const;
  ::galbot::core_proto::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::galbot::core_proto::Header* header);
  ::galbot::core_proto::Header* unsafe_arena_release_header();

  // uint64 sequence = 5;
  void clear_sequence();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequence() const;
  void set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequence() const;
  void _internal_set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:galbot.singorix_proto.EndToolRawCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr endpoint_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr channel_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
  ::galbot::core_proto::Header* header_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequence_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EndToolRawData

// .galbot.core_proto.Header header = 1;
inline bool EndToolRawData::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool EndToolRawData::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& EndToolRawData::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& EndToolRawData::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawData.header)
  return _internal_header();
}
inline void EndToolRawData::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.EndToolRawData.header)
}
inline ::galbot::core_proto::Header* EndToolRawData::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* EndToolRawData::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawData.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* EndToolRawData::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* EndToolRawData::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawData.header)
  return _internal_mutable_header();
}
inline void EndToolRawData::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawData.header)
}

// string endpoint_id = 2;
inline void EndToolRawData::clear_endpoint_id() {
  endpoint_id_.ClearToEmpty();
}
inline const std::string& EndToolRawData::endpoint_id() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawData.endpoint_id)
  return _internal_endpoint_id();
}
inline void EndToolRawData::set_endpoint_id(const std::string& value) {
  _internal_set_endpoint_id(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawData.endpoint_id)
}
inline std::string* EndToolRawData::mutable_endpoint_id() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawData.endpoint_id)
  return _internal_mutable_endpoint_id();
}
inline const std::string& EndToolRawData::_internal_endpoint_id() const {
  return endpoint_id_.Get();
}
inline void EndToolRawData::_internal_set_endpoint_id(const std::string& value) {
  
  endpoint_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void EndToolRawData::set_endpoint_id(std::string&& value) {
  
  endpoint_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.EndToolRawData.endpoint_id)
}
inline void EndToolRawData::set_endpoint_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  endpoint_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.EndToolRawData.endpoint_id)
}
inline void EndToolRawData::set_endpoint_id(const char* value,
    size_t size) {
  
  endpoint_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.EndToolRawData.endpoint_id)
}
inline std::string* EndToolRawData::_internal_mutable_endpoint_id() {
  
  return endpoint_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* EndToolRawData::release_endpoint_id() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawData.endpoint_id)
  return endpoint_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndToolRawData::set_allocated_endpoint_id(std::string* endpoint_id) {
  if (endpoint_id != nullptr) {
    
  } else {
    
  }
  endpoint_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), endpoint_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawData.endpoint_id)
}

// string channel_id = 3;
inline void EndToolRawData::clear_channel_id() {
  channel_id_.ClearToEmpty();
}
inline const std::string& EndToolRawData::channel_id() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawData.channel_id)
  return _internal_channel_id();
}
inline void EndToolRawData::set_channel_id(const std::string& value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawData.channel_id)
}
inline std::string* EndToolRawData::mutable_channel_id() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawData.channel_id)
  return _internal_mutable_channel_id();
}
inline const std::string& EndToolRawData::_internal_channel_id() const {
  return channel_id_.Get();
}
inline void EndToolRawData::_internal_set_channel_id(const std::string& value) {
  
  channel_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void EndToolRawData::set_channel_id(std::string&& value) {
  
  channel_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.EndToolRawData.channel_id)
}
inline void EndToolRawData::set_channel_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  channel_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.EndToolRawData.channel_id)
}
inline void EndToolRawData::set_channel_id(const char* value,
    size_t size) {
  
  channel_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.EndToolRawData.channel_id)
}
inline std::string* EndToolRawData::_internal_mutable_channel_id() {
  
  return channel_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* EndToolRawData::release_channel_id() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawData.channel_id)
  return channel_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndToolRawData::set_allocated_channel_id(std::string* channel_id) {
  if (channel_id != nullptr) {
    
  } else {
    
  }
  channel_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), channel_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawData.channel_id)
}

// bytes payload = 4;
inline void EndToolRawData::clear_payload() {
  payload_.ClearToEmpty();
}
inline const std::string& EndToolRawData::payload() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawData.payload)
  return _internal_payload();
}
inline void EndToolRawData::set_payload(const std::string& value) {
  _internal_set_payload(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawData.payload)
}
inline std::string* EndToolRawData::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawData.payload)
  return _internal_mutable_payload();
}
inline const std::string& EndToolRawData::_internal_payload() const {
  return payload_.Get();
}
inline void EndToolRawData::_internal_set_payload(const std::string& value) {
  
  payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void EndToolRawData::set_payload(std::string&& value) {
  
  payload_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.EndToolRawData.payload)
}
inline void EndToolRawData::set_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.EndToolRawData.payload)
}
inline void EndToolRawData::set_payload(const void* value,
    size_t size) {
  
  payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.EndToolRawData.payload)
}
inline std::string* EndToolRawData::_internal_mutable_payload() {
  
  return payload_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* EndToolRawData::release_payload() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawData.payload)
  return payload_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndToolRawData::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  payload_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), payload,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawData.payload)
}

// uint64 sequence = 5;
inline void EndToolRawData::clear_sequence() {
  sequence_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EndToolRawData::_internal_sequence() const {
  return sequence_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EndToolRawData::sequence() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawData.sequence)
  return _internal_sequence();
}
inline void EndToolRawData::_internal_set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequence_ = value;
}
inline void EndToolRawData::set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequence(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawData.sequence)
}

// -------------------------------------------------------------------

// EndToolRawCommand

// .galbot.core_proto.Header header = 1;
inline bool EndToolRawCommand::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool EndToolRawCommand::has_header() const {
  return _internal_has_header();
}
inline const ::galbot::core_proto::Header& EndToolRawCommand::_internal_header() const {
  const ::galbot::core_proto::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::galbot::core_proto::Header&>(
      ::galbot::core_proto::_Header_default_instance_);
}
inline const ::galbot::core_proto::Header& EndToolRawCommand::header() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawCommand.header)
  return _internal_header();
}
inline void EndToolRawCommand::unsafe_arena_set_allocated_header(
    ::galbot::core_proto::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:galbot.singorix_proto.EndToolRawCommand.header)
}
inline ::galbot::core_proto::Header* EndToolRawCommand::release_header() {
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::galbot::core_proto::Header* EndToolRawCommand::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawCommand.header)
  
  ::galbot::core_proto::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::galbot::core_proto::Header* EndToolRawCommand::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::galbot::core_proto::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::galbot::core_proto::Header* EndToolRawCommand::mutable_header() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawCommand.header)
  return _internal_mutable_header();
}
inline void EndToolRawCommand::set_allocated_header(::galbot::core_proto::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawCommand.header)
}

// string endpoint_id = 2;
inline void EndToolRawCommand::clear_endpoint_id() {
  endpoint_id_.ClearToEmpty();
}
inline const std::string& EndToolRawCommand::endpoint_id() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
  return _internal_endpoint_id();
}
inline void EndToolRawCommand::set_endpoint_id(const std::string& value) {
  _internal_set_endpoint_id(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
}
inline std::string* EndToolRawCommand::mutable_endpoint_id() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
  return _internal_mutable_endpoint_id();
}
inline const std::string& EndToolRawCommand::_internal_endpoint_id() const {
  return endpoint_id_.Get();
}
inline void EndToolRawCommand::_internal_set_endpoint_id(const std::string& value) {
  
  endpoint_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void EndToolRawCommand::set_endpoint_id(std::string&& value) {
  
  endpoint_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
}
inline void EndToolRawCommand::set_endpoint_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  endpoint_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
}
inline void EndToolRawCommand::set_endpoint_id(const char* value,
    size_t size) {
  
  endpoint_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
}
inline std::string* EndToolRawCommand::_internal_mutable_endpoint_id() {
  
  return endpoint_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* EndToolRawCommand::release_endpoint_id() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
  return endpoint_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndToolRawCommand::set_allocated_endpoint_id(std::string* endpoint_id) {
  if (endpoint_id != nullptr) {
    
  } else {
    
  }
  endpoint_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), endpoint_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawCommand.endpoint_id)
}

// string channel_id = 3;
inline void EndToolRawCommand::clear_channel_id() {
  channel_id_.ClearToEmpty();
}
inline const std::string& EndToolRawCommand::channel_id() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawCommand.channel_id)
  return _internal_channel_id();
}
inline void EndToolRawCommand::set_channel_id(const std::string& value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawCommand.channel_id)
}
inline std::string* EndToolRawCommand::mutable_channel_id() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawCommand.channel_id)
  return _internal_mutable_channel_id();
}
inline const std::string& EndToolRawCommand::_internal_channel_id() const {
  return channel_id_.Get();
}
inline void EndToolRawCommand::_internal_set_channel_id(const std::string& value) {
  
  channel_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void EndToolRawCommand::set_channel_id(std::string&& value) {
  
  channel_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.EndToolRawCommand.channel_id)
}
inline void EndToolRawCommand::set_channel_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  channel_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.EndToolRawCommand.channel_id)
}
inline void EndToolRawCommand::set_channel_id(const char* value,
    size_t size) {
  
  channel_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.EndToolRawCommand.channel_id)
}
inline std::string* EndToolRawCommand::_internal_mutable_channel_id() {
  
  return channel_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* EndToolRawCommand::release_channel_id() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawCommand.channel_id)
  return channel_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndToolRawCommand::set_allocated_channel_id(std::string* channel_id) {
  if (channel_id != nullptr) {
    
  } else {
    
  }
  channel_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), channel_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawCommand.channel_id)
}

// bytes payload = 4;
inline void EndToolRawCommand::clear_payload() {
  payload_.ClearToEmpty();
}
inline const std::string& EndToolRawCommand::payload() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawCommand.payload)
  return _internal_payload();
}
inline void EndToolRawCommand::set_payload(const std::string& value) {
  _internal_set_payload(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawCommand.payload)
}
inline std::string* EndToolRawCommand::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:galbot.singorix_proto.EndToolRawCommand.payload)
  return _internal_mutable_payload();
}
inline const std::string& EndToolRawCommand::_internal_payload() const {
  return payload_.Get();
}
inline void EndToolRawCommand::_internal_set_payload(const std::string& value) {
  
  payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void EndToolRawCommand::set_payload(std::string&& value) {
  
  payload_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:galbot.singorix_proto.EndToolRawCommand.payload)
}
inline void EndToolRawCommand::set_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:galbot.singorix_proto.EndToolRawCommand.payload)
}
inline void EndToolRawCommand::set_payload(const void* value,
    size_t size) {
  
  payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:galbot.singorix_proto.EndToolRawCommand.payload)
}
inline std::string* EndToolRawCommand::_internal_mutable_payload() {
  
  return payload_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* EndToolRawCommand::release_payload() {
  // @@protoc_insertion_point(field_release:galbot.singorix_proto.EndToolRawCommand.payload)
  return payload_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EndToolRawCommand::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  payload_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), payload,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:galbot.singorix_proto.EndToolRawCommand.payload)
}

// uint64 sequence = 5;
inline void EndToolRawCommand::clear_sequence() {
  sequence_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EndToolRawCommand::_internal_sequence() const {
  return sequence_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EndToolRawCommand::sequence() const {
  // @@protoc_insertion_point(field_get:galbot.singorix_proto.EndToolRawCommand.sequence)
  return _internal_sequence();
}
inline void EndToolRawCommand::_internal_set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequence_ = value;
}
inline void EndToolRawCommand::set_sequence(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequence(value);
  // @@protoc_insertion_point(field_set:galbot.singorix_proto.EndToolRawCommand.sequence)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace singorix_proto
}  // namespace galbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_galbot_2fsingorix_5fproto_2fsingorix_5fpassthrough_2eproto
